---
subject: Node.js agent
releaseDate: '2016-05-05'
version: 1.27.2
downloadLink: 'https://www.npmjs.com/package/newrelic'
---

### Bug fixes

* Fixed duplicated external transactions for `https` requests in Node > 0.10.

  Any external transaction that used the `https` module to make the request would appear twice in transaction traces due to `https.request` internally using `http.request`. This has now been resolved.
* Updated eslint dev dependency to 2.9.0 (was 0.24.1).
* Fixed an issue with transaction naming precedence.

  Custom naming of transactions will no longer be replaced by names generated by the instrumentation.
* Fixed tests which broke under Node 6.0.

  Node 6.0.0 changed some messaging and internal functionality which our tests were asserting on. These tests have been updated to work with either the new version or the older ones.
* Fixed installing GCC 5 in Travis for testing native modules in Node >= 3.0.

  Starting in Node 3.0, native modules were compiled with C++11 features enabled. The version of GCC preinstalled on Travis was too old to support that so we now manually install GCC 5 and set it as the system compiler.
* Fixed metrics that were being scoped to themselves.

  Some metrics were scoped to themselves, causing a strange visual glitch in the New Relic UI. This self-scoping has been removed.
* Added tests for transaction naming with parallel requests in Express.
