# Set to true to add reviewers to pull requests
addReviewers: true

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - paperclypse
  - rhetoric101
  - homelessbirds
  - x8a
  - nbaenam
  - a-sassman
  - stumblefiend
  - zuluecho9
  - ally-sassman
  - akristen
  - jeff-colucci
  - bradleycamacho

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 1

filterLabels:
  # Run
  include:
    - from_tw
 
