[[plugins]]
package = "@netlify/plugin-gatsby"

[functions]
  included_files = ["!.cache/data/datastore/data.mdb","!.cache/query-engine"]

[[edge_functions]]
  path = "/*"
  function = "osano-country"

[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "*"
Referrer-Policy="no-referrer-when-downgrade"
Content-Security-Policy="frame-ancestors *.newrelic.com"
