[[plugins]]
package = "@netlify/plugin-gatsby"

[functions]
  included_files = ["!.cache/data/datastore/data.mdb","!.cache/query-engine"]

[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "*"