[[plugins]]
package = "@netlify/plugin-gatsby"

[functions]
  included_files = ["!.cache/data/datastore/data.mdb","!.cache/query-engine"]

# Edge functions commented out to avoid costs
# Uncomment if country-based functionality is needed again
# [[edge_functions]]
#   function = "inject-country" # Matches the filename without .js
#   path = "/*" # Apply to all HTML pages served by Netlify


[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "*"
Referrer-Policy="no-referrer-when-downgrade"
Content-Security-Policy="frame-ancestors *.newrelic.com"

[build.environment]
 NETLIFY_IMAGE_CDN = "true"