---
title: プロキシ エージェント コードと分析データ
tags:
  - Browser monitoring
  - Proxy
metaDescription: The agent can be configured to fetch its code and send analytics through a proxy server instead of New Relic's endpoints.
freshnessValidatedDate: '2023-09-22T00:00:00.000Z'
translationType: machine
---

<Callout variant="important">
  この機能は現在、コピー/ペーストまたは NPM ブラウザーのインストール方法を使用しているユーザーが利用できます。現在、利用可能な UI または NerdGraph 構成オプションはありません。私たちは、これらおよびその他の構成オプションへのアクセスを改善するために引き続き取り組んでいます。
</Callout>

BrowserAgent のプロキシ URL を設定することは、パフォーマンスを目的として監視データが確実に収集されるようにするための貴重な方法となります。

プロキシ方式を使用する場合は、エンドユーザーおよび/またはサイト訪問者に対する契約上、規制上、またはその他の法的義務に基づいてプロキシ方式を使用する権利があることを確認することが重要です。 この方法が組織にとって実行可能で準拠したソリューションであることが確認できた場合は、以下の設定手順を参照してください。

## 使い方 [#how-it-works]

ブラウザ エージェント[バージョン 1.240.0](/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes)以降では、転送するデータの種類に応じて 2 つの異なるタイプのプロキシを設定できます。ブラウザ エージェント コードを取得するプロキシと、分析データを New に転送するプロキシです。遺物。

これらのプロキシを設定するには、次のブラウザ エージェント プロパティを構成する必要があります。

* `init.proxy.assets` ブラウザエージェントを取得する場所を決定します。

  * コピー/ペーストのインストール方法を使用している場合は、JavaScript スニペットを手動で編集し、 `assets`をドメイン URL に設定する必要があります。
  * たとえば、ブラウザ エージェント v1.240.0 を使用している場合Pro+SPA の場合、 `init.proxy.assets`を`assets.mydomain.com`に設定すると、ブラウザ エージェントは`https://js-agent.newrelic.com/nr-spa.<hash>-1.240.0.min.js`ではなく`https://assets.mydomain.com/nr-spa.<hash>-1.240.0.min.js`からロードされます。
  * NPM インストール方法を使用している場合、この構成は関係ありません。NPM にインストールされたブラウザー エージェントは、ホスト アプリケーションと同じバンドル プロセスを経て、ホスト アプリケーションと並んで`output`ディレクトリにエージェント アセットが作成されます。ホスト アプリケーションがデプロイされると、これらのエージェント アセットもデプロイされる必要があり、その結果、エージェント コードがサイトと同じドメインからすでに読み込まれます。

* `init.proxy.beacon` 分析データの送信先を決定します。

  * どちらのインストール方法でも、 `beacon`ドメイン URL に設定する必要があります。
  * たとえば、 `beacon`を`beacon.mydomain.com`に設定すると、すべての可観測性データが`https://beacon.mydomain.com/OBSERVABILITY_ENDPOINT`に送信されます。

ユーザーのプライバシーが心配な場合は、クライアントの地理的位置を特定するために使用される`X-Forwarded-For HTTP`ヘッダーを除外できます。これを除外すると、New Relic は代わりにプロキシをクライアントとして位置特定します。

## 始めましょう [#set-up]

プロキシへのリクエストのリダイレクトを開始するには、ブラウザ エージェントのインストールに使用した展開方法に基づいて、以下の手順を参照してください。

### 推奨事項

これらのプロパティを構成するときは、次のことをお勧めします。

* ファーストパーティのサブドメインを使用します。技術的には別のサードパーティ ドメインを使用できますが、広告ブロッカーやセキュリティ VPN によってブロックされる可能性があります。
* 入力パターンは`<domain>[:<port>][/<path>]`です。プロトコル ( `https://`など) と終了スラッシュを必ず省略してください。`port`と`path`はオプションであり、追加された場合は尊重されます。
* `assets`と`beacon`の両方を構成している場合は、異なるサブドメインまたは異なるパスを使用して、プロキシごとに異なる値を設定します。これにより、プロキシ サーバーの構成が非常に簡単になります。

### コピー＆ペーストでインストール [#copy-paste]

コピー/ペーストのインストール方法を使用している場合は、エージェント ローダーの前にブラウザの JavaScript 設定に次の設定を追加します。

```js
window.NREUM.init = {
    ...<other init properties>,
    proxy: {
        assets: <URL string>
        beacon: <URL string>
    }
}
```

### NPMのインストール [#npm]

NPM ブラウザーのインストール方法を使用している場合は、ブラウザー エージェントの初期化時に次の構成を追加します。

```js
new BrowserAgent({ 
  init: {
    ...<other init properties>,
    proxy: {
        beacon: <URL string>
    }
  }
})
```

## プロキシの使用 [#using-proxies]

New Relic はクラウド プロキシ サービスを提供またはサポートしていないため、独自のプロキシ サーバーを構成および管理する必要があります。完全な機能を保証するために、プロキシについて次のことを前提としています。

* <DNT>
    **Load the browser agent code from the New Relic CDN and pass it back to the client.**
  </DNT>

  `assets`フィールドを使用している場合、プロキシは`https://js-agent.newrelic.com/`からブラウザエージェント コードをロードし、それをクライアントに返す必要があります。 たとえば、BrowserAgent v1.240.0 の場合、 `https://assets.mydomain.com/nr-spa.3b61d78f-1.240.0.min.js`へのリクエストは、上流の`https://js-agent.newrelic.com/nr-spa.3b61d78f-1.240.0.min.js`からのレスポンスと同じレスポンスを返す必要があります。

* <DNT>
    **Forward client payloads to New Relic.**
  </DNT>

  `beacon`プロキシはクライアント ペイロードを New Relic に転送します。 元のエンドポイントは、[ブラウザのアプリケーション設定ページ](/docs/browser/new-relic-browser/configuration/browser-app-settings-page/)で見つけることができます。 JavaScript スニペットで、 `;NREUM.info={beacon:"_____",...`を探します。 ほとんどのアプリでは、これは`(https://)bam.nr-data.net`になります。 ただし、コンプライアンスや法的理由により異なる場合があります。 たとえば、 `https://yourproxy.com/1/asdf?a=123`へのリクエストは`https://bam.nr-data.net/1/asdf?a=123`にパススルーされる必要があります。

* <DNT>
    **Do not modify requests and responses.**
  </DNT>

  プロキシ サーバー経由のリクエストと応答は変更しないでください。

* <DNT>
    **Support the bandwidth and traffic generated by observability data collection.**
  </DNT>

  システムはプロキシ負荷をサポートできる必要がありますが、生成されるデータの量はサイトの使用状況によって異なります。
