---
title: 프록시 에이전트 코드 및 분석 데이터
tags:
  - Browser monitoring
  - Proxy
metaDescription: The agent can be configured to fetch its code and send analytics through a proxy server instead of New Relic's endpoints.
freshnessValidatedDate: '2023-09-22T00:00:00.000Z'
translationType: machine
---

<Callout variant="important">
  이 기능은 현재 복사/붙여넣기 또는 NPM 브라우저 설치 방법을 사용하는 사용자에게 제공됩니다. 현재 사용 가능한 UI 또는 NerdGraph 구성 옵션이 없습니다. 우리는 이러한 구성 옵션과 기타 구성 옵션에 대한 액세스를 개선하기 위해 지속적으로 노력하고 있습니다.
</Callout>

브라우저 에이전트에 대한 프록시 URL을 설정하는 것은 옵저버빌리티 데이터가 성능 목적으로 계속 수집되도록 하는 중요한 방법이 될 수 있습니다.

프록시 방법을 사용할 때는 최종 사용자 및/또는 사이트 방문자에 대해 가질 수 있는 계약, 규제 또는 기타 법적 의무에 따라 프록시 방법을 사용할 권리가 있는지 확인하는 것이 중요합니다. 이 방법이 조직에서 실행 가능하고 규정을 준수하는 솔루션임을 확인한 경우 아래 설정 지침을 살펴보세요.

## 작동 원리 [#how-it-works]

브라우저 에이전트 [버전 1.240.0](/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes) 이상부터, 전달하려는 데이터의 종류에 따라 두 가지 유형의 프록시, 즉 브라우저 에이전트 코드를 가져오는 프록시와 분석 데이터를 New Relic에 전달하는 프록시를 설정할 수 있습니다.

이러한 프록시를 설정하려면 다음 브라우저 에이전트 속성을 구성해야 합니다.

* `init.proxy.assets` 브라우저 에이전트를 가져올 위치를 결정합니다.

  * 복사/붙여넣기 설치 방법을 사용하는 경우 JavaScript 스니펫을 수동으로 편집하고 `assets` 도메인 URL로 설정해야 합니다.
  * 예를 들어 브라우저 에이전트 v1.240.0을 사용하는 경우 Pro+SPA를 사용하고 `init.proxy.assets` `assets.mydomain.com` 로 설정하면 브라우저 에이전트가 `https://js-agent.newrelic.com/nr-spa.<hash>-1.240.0.min.js` 대신 `https://assets.mydomain.com/nr-spa.<hash>-1.240.0.min.js` 에서 로드됩니다.
  * NPM 설치 방법을 사용하는 경우 이 구성은 관련이 없습니다. NPM이 설치된 브라우저 에이전트는 호스트 애플리케이션과 동일한 번들링 프로세스를 거치며 호스트 애플리케이션과 함께 `output` 디렉터리에 에이전트 자산이 생성되어야 합니다. 호스트 응용 프로그램이 배포되면 해당 에이전트 자산도 배포되어야 하며 결과적으로 에이전트 코드는 사이트와 동일한 도메인에서 이미 로드되어야 합니다.

* `init.proxy.beacon` 분석 데이터가 전송되는 위치를 결정합니다.

  * 두 가지 설치 방법 모두 `beacon` 도메인 URL로 설정해야 합니다.
  * 예를 들어, `beacon` `beacon.mydomain.com` 로 설정하면 모든 관측 가능성 데이터가 `https://beacon.mydomain.com/OBSERVABILITY_ENDPOINT` 로 전송됩니다.

사용자 개인 정보 보호가 우려되는 경우 클라이언트의 위치 정보를 찾는 데 사용되는 `X-Forwarded-For HTTP` 헤더를 제외할 수 있습니다. 이를 제외하면 New Relic은 대신 프록시를 클라이언트로 위치 지정합니다.

## 시작하다 [#set-up]

요청을 프록시로 리디렉션하려면 브라우저 에이전트를 설치하는 데 사용한 배포 방법에 따라 아래 지침을 참조하세요.

### 권장 사항

이러한 속성을 구성할 때 다음을 권장합니다.

* 자사 하위 도메인을 사용하세요. 기술적으로 다른 타사 도메인을 사용할 수 있더라도 광고 차단기 및 보안 VPN에 의해 차단될 가능성이 높습니다.
* 입력 패턴은 `<domain>[:<port>][/<path>]` 입니다. 프로토콜(예: `https://`)과 끝 슬래시를 생략해야 합니다. `port` 및 `path` 은 선택사항이며 추가되면 적용됩니다.
* `assets` 및 `beacon` 모두 구성하는 경우 다른 하위 도메인이나 다른 경로를 사용하여 각 프록시에 대해 다른 값을 설정하십시오. 이렇게 하면 프록시 서버 구성이 훨씬 쉬워집니다.

### 복사/붙여넣기 설치 [#copy-paste]

복사/붙여넣기 설치 방법을 사용하는 경우 에이전트 로더 전에 브라우저 JavaScript 구성에 다음 구성을 추가하세요.

```js
window.NREUM.init = {
    ...<other init properties>,
    proxy: {
        assets: <URL string>
        beacon: <URL string>
    }
}
```

### NPM 설치 [#npm]

NPM 브라우저 설치 방법을 사용하는 경우 브라우저 에이전트를 초기화할 때 다음 구성을 추가하세요.

```js
new BrowserAgent({ 
  init: {
    ...<other init properties>,
    proxy: {
        beacon: <URL string>
    }
  }
})
```

## 프록시 사용 [#using-proxies]

New Relic 클라우드 프록시 서비스를 제공하거나 지원하지 않으므로 프록시 서버를 직접 구성하고 관리해야 합니다. 전체 기능을 보장하기 위해 프록시에 대해 다음과 같이 가정합니다.

* <DNT>
    **Load the browser agent code from the New Relic CDN and pass it back to the client.**
  </DNT>

  `assets` 필드를 사용하는 경우 프록시는 `https://js-agent.newrelic.com/` 에서 브라우저 에이전트 코드를 로드하고 이를 클라이언트에 다시 전달해야 합니다. 예를 들어 브라우저 에이전트 v1.240.0의 경우 `https://assets.mydomain.com/nr-spa.3b61d78f-1.240.0.min.js` 에 대한 요청은 업스트림 `https://js-agent.newrelic.com/nr-spa.3b61d78f-1.240.0.min.js` 에서와 동일한 응답을 생성해야 합니다.

* <DNT>
    **Forward client payloads to New Relic.**
  </DNT>

  `beacon` 프록시는 클라이언트 페이로드를 뉴렐릭으로 전달합니다. 원래 엔드포인트는 [브라우저 애플리케이션 설정 페이지](/docs/browser/new-relic-browser/configuration/browser-app-settings-page/) 에서 찾을 수 있습니다. JavaScript 스니펫에서 `;NREUM.info={beacon:"_____",...` 찾으세요. 대부분의 앱에서 이는 `(https://)bam.nr-data.net` 입니다. 그러나 규정 준수 및 법적 이유로 인해 달라질 수 있습니다. 예를 들어, `https://yourproxy.com/1/asdf?a=123` 에 대한 요청은 `https://bam.nr-data.net/1/asdf?a=123` 로 전달되어야 합니다.

* <DNT>
    **Do not modify requests and responses.**
  </DNT>

  프록시 서버를 통한 요청 및 응답은 수정되어서는 안 됩니다.

* <DNT>
    **Support the bandwidth and traffic generated by observability data collection.**
  </DNT>

  시스템은 프록시 로드를 지원할 수 있어야 하지만 생성되는 데이터의 양은 사이트 사용량에 따라 달라집니다.
