---
title: Aporia integration
metaDescription: "Send your machine learning model data from Aporia to New Relic to understand your model's performance."
redirects:
  - /docs/integrations/mlops-integrations/aporia-mlops-integration
  - /docs/alerts-applied-intelligence/applied-intelligence/mlops-integrations/aporia-mlops-integration
  - /docs/alerts-applied-intelligence/mlops/integrations/aporia-mlops-integration
freshnessValidatedDate: never
---

Aporia is a fast, easy, and secure way for data science teams to monitor their machine learning models in production. With Aporia, teams can build their own customizable monitors in minutes to receive live alerts for early detection of issues like data drift, unexpected bias, data integrity issues, and performance degradation. Aporia also has an investigation toolbox to enable further investigation and root cause analysis. [Learn more about Aporia](https://www.aporia.com).

Aporia includes an integration with New Relic to provide full model management of your MLOps infrastructure, with customized <InlinePopover type="dashboards"/> within New Relic that show inferences investigation.

## Integrate Aporia with New Relic [#integrate-aporia]

Aporia allows you to connect <InlinePopover type="alerts"/> generated by Aporia's monitors to New Relic's incident intelligence engine and the predictions data in order to create a comprehensive monitoring dashboard in New Relic for your models.

1. <DNT>**Login into Aporia's console**</DNT>: On the navbar on the left, click on <DNT>**Integrations**</DNT> and choose <DNT>**New Relic**</DNT>.
2. <DNT>**Login into your New Relic account:**</DNT> Go to <DNT>**[one.newrelic.com > All capabilities](https://one.newrelic.com/all-capabilities) > +Add more data**</DNT>.
3. <DNT>**Click on Aporia:**</DNT> In the search bar, type <DNT>**Aporia**</DNT>.
4. <DNT>**Select your account ID:**</DNT> Select the account ID you want Aporia to integrate with.
5. <DNT>**Get a New Relic API key:**</DNT> Once you click on the Aporia icon, follow step one. Under <DNT>**Prediction data & model quality alerts**</DNT>, click either <DNT>**Select**</DNT>, to choose an existing key, or <DNT>**Create API key**</DNT>. This created a New Relic <InlinePopover type="licenseKey"/>, which is used for reporting data to New Relic.
6. <DNT>**Paste the key in Aporia:**</DNT> Now go to Aporia's dashboard and under the New Relic Integration screen, paste the key under <DNT>**New Relic insert token**</DNT>. Once pasted, click <DNT>**Save**</DNT>.
7. <DNT>**Verify the key:**</DNT> In the Aporia dashboard, click on the <DNT>**Verify token**</DNT> button to verify the key is working properly. A <DNT>**Green**</DNT> check mark or <DNT>**Red**</DNT> error marks should appear to indicate the status.

<InstallFeedback/>

## Monitor your machine learning models with Aporia

Now that you've integrated New Relic and Aporia, you can monitor your data using [dashboards](/docs/query-your-data/explore-query-data/dashboards/introduction-dashboards/) with automated charts created by Aporia.

1. <DNT>**Go to the integration dashboard:**</DNT> Once you've verified your tokens and confirmed the integration is set up correctly, return to the New Relic integration dashboard and click on <DNT>**See your data**</DNT>. This will redirect you to an automatically generated dashboard displaying data reported to Aporia in New Relic.

2. <DNT>**Analyze Aporia's dashboard.**</DNT> Aporia's dashboard populated in New Relic contains 6 charts:

   * The <DNT>**Most active models**</DNT> chart displays the different models which reported predictions in the selected timeframe.
   * The <DNT>**Most active model versions**</DNT> chart displays the different versions which reported predictions in the selected timeframe.
   * The <DNT>**Model inferences**</DNT> graph displays the number of unique predictions reported for each model and version.
   * The <DNT>**Average numeric inferences**</DNT> chart displays the average value numeric predictions reported for each model and version.
   * The <DNT>**Numeric inferences heatmaps**</DNT> chart displays a histogram of the numeric predictions reported for each model and version.
   * The <DNT>**Categorical inferences**</DNT> charts display the different unique values and their frequencies of categorical predictions reported for each model and version.

   <img
     title="An image of the Aporia dashboard"
     alt="An image of the Aporia dashboard."
     src="/images/model-performance-monitoring_screenshot-full_aporia-dashboard.webp"
   />

3. <DNT>**Filter data:**</DNT> Click on the <DNT>**…**</DNT> button and click on <DNT>**Edit**</DNT>. On the right navbar, under <DNT>**User as filter**</DNT>, enable <DNT>**Filter the current dashboard**</DNT> and click <DNT>**Save**</DNT>.

4. <DNT>**Setup alert notifications:**</DNT> Once you've created some dashboards, you can get alerted on your data. To create a NRQL alerts condition from a chart, click the chart widget, then click <DNT>**Create alert condition**</DNT>. Once you've named and customized your condition, you can add it to an existing policy or create a new one.

   <img
     title="Set up notifications for Aporia"
     alt="Set up notifications for Aporia."
     src="/images/model-performance-monitoring_screenshot-crop_aporia-create-alert.webp"
   />

5. <DNT>**Get notified:**</DNT> Once you've created an alerts condition, you can choose how you want to be notified. See our docs on [how to set up notification channels](/docs/alerts-applied-intelligence/new-relic-alerts/alert-notifications/notification-channels-control-where-send-alerts).

6. <DNT>**Correlate your incidents:**</DNT> In addition to notifications, you can use incident intelligence to correlate your incidents. See our docs on [how to correlate incidents using decisions](/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/change-applied-intelligence-correlation-logic-decisions).

<img
  title="Correlate your incidents for Aporia"
  alt="Correlate your incidents for Aporia."
  src="/images/model-performance-monitoring_screenshot-crop_aporia-correlation.webp"
/>
