---
subject: Python agent
releaseDate: '2018-05-16'
version: 3.2.1.93
downloadLink: 'https://pypi.python.org/pypi/newrelic'
redirects:
  - /docs/release-notes/agent-release-notes/python-release-notes/python-agent-32192
---

## Notes

This release of the Python agent contains various bug fixes.

The agent can be installed using easy_install/pip/distribute via the [Python Package Index](https://pypi.python.org/pypi/newrelic) or can be downloaded directly from the New Relic [download site](https://download.newrelic.com/python_agent/release).

## Bug Fixes

* **Do not run explain plans for psycopg2 connections using the `async_` kwarg**

  As "async" is now a keyword in Python 3.7, psycopg2 now allows "async\_" as an alias for its "async" kwarg for psycopg2.connect as of psycopg2 v2.7.4. Previously, explain plans were attempted for these connections and a traceback would be seen in the logs. This has now been fixed.
* **Fix traceback when using callbacks as partials in pika consumers**

  When passing a callback that is a functools partial to pika channel consumers, a traceback occurred in some instances. This issue has now been fixed.
* **cx_Oracle database calls that use SessionPool objects were not recorded**

  When using the cx_Oracle SessionPool interace, database transactions made through the acquired pool connection may not have been reported. Database transactions that using connections generated by SessionPool are now reported as expected.
* **SQL targets for call statements may contain a period**

  For a SQL command like `CALL foo.bar(:baz)`, APM would show metrics under the target name `foo` instead of the full name `foo.bar`. This has been fixed.
