---
subject: Python agent
releaseDate: '2017-05-26'
version: 2.86.3.70
downloadLink: 'https://pypi.python.org/pypi/newrelic'
redirects:
  - /docs/release-notes/agent-release-notes/python-release-notes/python-agent-286369
---

## Notes

This release of the Python agent includes various bug fixes as described below.

The agent can be installed using easy_install/pip/distribute via the [Python Package Index](https://pypi.python.org/pypi/newrelic) or can be downloaded directly from the New Relic [download site](https://download.newrelic.com/python_agent/release/).

## Bug Fixes

* **Handle exceptions generated by [Tornado 4](/docs/agents/python-agent/hosting-mechanisms/introductory-tornado-4-support) AsyncHTTPClient during fetch**

  Exceptions generated by a call to the AsyncHTTPClient resulted in an agent instrumentation error. Exceptions generated by AsyncHTTPClient are now recorded and properly handled.
* **Using gevent/eventlet on Python 3.6 resulted in a RecursionError**

  Python 3.6 introduced a [change](https://github.com/python/cpython/commit/328067c468f82e4ec1b5c510a4e84509e010f296) to the ssl library. This change can result in a [recursion error](https://bugs.python.org/issue29149) when the New Relic agent imports ssl prior to eventlet/gevent patching the ssl library (as is the case with use of the newrelic-admin script). This recursion error has been fully mitigated.
