---
title: AWS Storage Gateway Metrics Integration
metaDescription: "New Relic's AWS Storage Gateway integration: what data it reports and how to enable it."
freshnessValidatedDate: 2024-03-08
---

New Relic infrastructure integrations now include an integration that sends your AWS Storage Gateway metrics to New Relic. The AWS Storage Gateway Metrics integration collects and sends telemetry data to New Relic from your AWS Storage Gateway. You can monitor your AWS services, query incoming data, and build dashboards to observe everything at a glance.

## Activate integration [#activate-ingration]

To enable this integration, follow the instructions in our [Amazon CloudWatch Metric Streams integration documentation](/docs/infrastructure/amazon-integrations/connect/aws-metric-stream-setup/).

## Find and use data [#find-data]

To find your integration's metrics:

1. Go to **[one.newrelic.com > All capabilities](https://one.newrelic.com/all-capabilities)**
2. Select **Metrics and events**
3. Filter by `aws.storagegateway`.

## Metric data [#metrics]

This New Relic infrastructure integration collects the following AWS Storage Gateway metrics:

### AWS Storage Gateway dimensions

<table>
  <thead>
    <tr>
      <th style={{ width: "200px" }}>
        Dimension  

      </th>

      <th>
        Description
      </th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        `GatewayId, GatewayName`
      </td>

      <td>
        These dimensions filter the data that you request to gateway-specific metrics.
      </td>
    </tr>
  </tbody>
</table>

### AWS Storage Gateway Metric data [#storage-gateway-metric-data]

<table>
  <thead>
    <tr>
      <th style={{ width: "200px" }}>
        Metric (min, max, average, count, sum)  

      </th>

      <th>
        Unit  

      </th>

      <th>
        Description
      </th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        `AvailabilityNotifications`
      </td>

      <td>
        Count
      </td>

      <td>
        This metric reports the number of availability-related health notifications that were generated by the gateway in the reporting period.
      </td>
    </tr>

    <tr>
      <td>
        `HealthNotifications`
      </td>

      <td>
        Count
      </td>

      <td>
        This metric reports the number of health notifications that were generated by this gateway in the reporting period.
      </td>
    </tr>

    <tr>
      <td>
        `FileSharesUnavailable`
      </td>

      <td>
        Sum
      </td>

      <td>
        This metric provides the number of file shares on this gateways which are in the Unavailable state.
      </td>
    </tr>

    <tr>
      <td>
        `WorkingStoragePercentUsed`
      </td>

      <td>
        Average
      </td>

      <td>
        Percent use of the gateway's upload buffer.
      </td>
    </tr>

    <tr>
      <td>
        `UserCpuPercent`
      </td>

      <td>
        Count
      </td>

      <td>
        Percent of CPU time spent on gateway processing, averaged across all cores
      </td>
    </tr>

    <tr>
      <td>
        `UploadBufferPercentUsed`
      </td>

      <td>
        Average
      </td>

      <td>
        Percent use of the gateway's upload buffer.
      </td>
    </tr>

    <tr>
      <td>
        `CloudBytesUploaded`
      </td>

      <td>
        Count
      </td>

      <td>
        The number of bytes uploaded from the cloud to the volume.
      </td>
    </tr>

    <tr>
      <td>
        `CloudBytesDownloaded`
      </td>

      <td>
        Count
      </td>

      <td>
        The number of bytes downloaded from the cloud to the volume.
      </td>
    </tr>

    <tr>
      <td>
        `ReadTime`
      </td>

      <td>
        Sum
      </td>

      <td>
        The total number of milliseconds spent on read operations from your on-premises applications in the reporting period.
      </td>
    </tr>

    <tr>
      <td>
        `WriteTime`
      </td>

      <td>
        Sum
      </td>

      <td>
        The total number of milliseconds spent on write operations from your on-premises applications in the reporting period
      </td>
    </tr>

    <tr>
      <td>
        `QueuedWrites`
      </td>

      <td>
        Average
      </td>

      <td>
        The number of bytes waiting to be written to AWS, sampled at the end of the reporting period for all volumes in the gateway. These bytes are kept in your gateway's working storage.
      </td>
    </tr>

    <tr>
      <td>
        `ReadBytes`
      </td>

      <td>
        Sum
      </td>

      <td>
        The total number of bytes read from your on-premises applications in the reporting period.
      </td>
    </tr>

    <tr>
      <td>
        `WriteBytes`
      </td>

      <td>
        Sum
      </td>

      <td>
        The total number of bytes written to your on-premises applications in the reporting period.
      </td>
    </tr>

    <tr>
      <td>
        `FilesFailingUpload`
      </td>

      <td>
        Sum
      </td>

      <td>
        This metric tracks the number of files which are failing to upload to AWS. These files will generate health notifications which contain more information on the issue.
      </td>
    </tr>

    <tr>
      <td>
        `SmbV1Sessions`
      </td>

      <td>
        Count
      </td>

      <td>
        This metric reports the number of SMBv1 sessions that are active on the gateway
      </td>
    </tr>

    <tr>
      <td>
        `SmbV2Sessions`
      </td>

      <td>
        Count
      </td>

      <td>
        This metric reports the number of SMBv2 sessions that are active on the gateway.
      </td>
    </tr>

    <tr>
      <td>
        `SmbV3Sessions`
      </td>

      <td>
        Count
      </td>

      <td>
        This metric reports the number of SMBv3 sessions that are active on the gateway.
      </td>
    </tr>

    <tr>
      <td>
        `WorkingStorageFree`
      </td>

      <td>
        Bytes
      </td>

      <td>
        The total amount of unused space in the gateway's working storage.
      </td>
    </tr>

    <tr>
      <td>
        `WorkingStorageUsed`
      </td>

      <td>
        Sum
      </td>

      <td>
        The total number of bytes being used in the gateway's upload buffer.
      </td>
    </tr>

    <tr>
      <td>
        `TotalCacheSize`
      </td>

      <td>
        Average
      </td>

      <td>
        This metric reports the total size of the cache.
      </td>
    </tr>

    <tr>
      <td>
        `CacheFileSize`
      </td>

      <td>
        Max
      </td>

      <td>
        This metric tracks the size of files in the gateway cache.
      </td>
    </tr>

    <tr>
      <td>
        `CacheDirectorySize`
      </td>

      <td>
        Max
      </td>

      <td>
        This metric tracks the size of folders in the gateway cache. Folder size is determined by the number of files and subfolders in its first level, this does not count recursively into subfolders.
      </td>
    </tr>

    <tr>
      <td>
        `CacheFree`
      </td>

      <td>
        Sum
      </td>

      <td>
        This metric reports the number of available bytes in the gateway cache.
      </td>
    </tr>

    <tr>
      <td>
        `CacheUsed`
      </td>

      <td>
        Sum
      </td>

      <td>
        This metric reports the number of used bytes in the gateway cache.
      </td>
    </tr>

    <tr>
      <td>
        `CacheHitPercent`
      </td>

      <td>
        Average
      </td>

      <td>
        Percent of application read operations from the gateway that are served from cache.
      </td>
    </tr>

    <tr>
      <td>
        `CachePercentDirty`
      </td>

      <td>
        Average
      </td>

      <td>
        The overall percentage of the gateway cache that has not been persisted to AWS
      </td>
    </tr>

    <tr>
      <td>
        `CachePercentUsed`
      </td>

      <td>
        Average
      </td>

      <td>
        The overall percent of the gateway cache storage that is used.
      </td>
    </tr>

    <tr>
      <td>
        `FileSharesUnavailable`
      </td>

      <td>
        Sum
      </td>

      <td>
        This metric provides the number of file shares on this gateways which are in the Unavailable state.
      </td>
    </tr>

    <tr>
      <td>
        `MemTotalBytes`
      </td>

      <td>
        Average
      </td>

      <td>
        This metric reports the total amount of memory on the gateway.
      </td>
    </tr>

    <tr>
      <td>
        `MemUsedBytes`
      </td>

      <td>
        Average
      </td>

      <td>
        This metric reports the amount of used memory on the gateway.
      </td>
    </tr>

    <tr>
      <td>
        `UploadBufferUsed`
      </td>

      <td>
        Sum
      </td>

      <td>
        The total number of bytes being used in the gateway's upload buffer.
      </td>
    </tr>
  </tbody>
</table>
