---
subject: PHP agent
releaseDate: '2015-07-08'
version: 4.23.0.102
---

<Callout variant="important">
  The end-of-life date for this agent version is July 29, 2019. To update to the latest agent version, see [Update the agent](/docs/agents/manage-apm-agents/installation/update-new-relic-agent). For more information, see [End-of-life policy](/docs/agents/manage-apm-agents/maintenance/new-relic-agent-plugin-end-life-policy).
</Callout>

### New Features

* Exceptions that are uncaught and handled only by a last resort exception handler installed via [`set_exception_handler()`](http://php.net/set_exception_handler) will now generate errors that can be viewed in the APM UI. Previously they would not be sent to New Relic at all.

  As a result of this, some customers will see more errors in the APM UI than they had previously seen.

### Bug Fixes

* In certain circumstances, such as an exception being thrown during database connection, errors generated by uncaught exceptions could result in the stack trace shown in APM including function argument values, which could potentially expose database passwords and other sensitive information. This problem has been fixed.

  We now catch these formerly-uncaught exceptions and thus have control over how the stack trace is built, ensuring that function argument values will no longer show up in those stack traces.
