---
subject: Containerized private minion (CPM)
redirects:
  - /docs/release-notes/synthetics-release-notes/containerized-private-minions-release-notes/feed
  - /docs/release-notes/synthetics-release-notes/private-minions-release-notes/private-minion-151
  - /docs/release-notes/synthetics-release-notes/private-minions-release-notes/private-minion-152
  - /docs/release-notes/synthetics-release-notes/private-minions-release-notes/private-minion-153
  - /docs/release-notes/synthetics-release-notes/private-minions-release-notes/private-minion-160
  - /docs/release-notes/synthetics-release-notes/private-minions-release-notes/private-minion-161
  - /docs/release-notes/synthetics-release-notes/private-minions-release-notes/private-minion-163
  - /docs/release-notes/synthetics-release-notes/private-minions-release-notes/private-minion-164
  - /docs/release-notes/synthetics-release-notes/private-minions-release-notes/private-minion-165
  - /docs/release-notes/synthetics-release-notes/private-minions-release-notes/private-minion-166
  - /docs/release-notes/synthetics-release-notes/private-minions-release-notes/private-minion-167
  - /docs/release-notes/synthetics-release-notes/private-minions-release-notes/private-minion-168
  - /docs/release-notes/synthetics-release-notes/private-minions-release-notes/private-minion-169
  - /docs/release-notes/synthetics-release-notes/vm-private-minions-release-notes-legacy/private-minion-170
  - /docs/release-notes/synthetics-release-notes/vm-private-minions-release-notes-legacy/private-minion-171
  - /docs/release-notes/synthetics-release-notes/private-minion-151
  - /docs/release-notes/synthetics-release-notes/private-minion-300
  - /docs/release-notes/private-minion
  - /docs/release-notes/synthetics-release-notes/private-minion-153-0
  - /docs/release-notes/synthetics-release-notes/vm-private-minions-release-notes-legacy/private-minion-213
  - /docs/release-notes/synthetics-release-notes/vm-private-minions-release-notes-legacy
  - /docs/synthetics/synthetic-monitoring/getting-started/containerized-private-minions-cpm-release-note
---
