const ERROR_TYPES = {
  MDX_ERROR: 'MDX_ERROR',
  FRONTMATTER_ERROR: 'FRONTMATTER_ERROR',
  FRONTMATTER_FIELD_ERROR: 'FRONTMATTER_FIELD_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
};

module.exports = ERROR_TYPES;
