agentName: ai-monitoring
agentType: aimon
title: 'Install AI monitoring'
metaDescription: 'Track the performance of your entire AI stack.'
introFilePath: 'src/install/ai-monitoring/intro.mdx'
appInfo:
  - optionType: agent-lang
    label: ''
    placeholder: 'What language is your AI-powered app written in?'
    options:
      - value: 'go'
        displayName: 'Go'
        logo: 'go'
      - value: 'java'
        displayName: 'Java'
        logo: 'java'
      - value: 'jupyter'
        displayName: 'Python (Jupyter Notebook or script)'
        logo: 'jupyter'
      - value: 'dotnet'
        displayName: '.NET'
        logo: 'dotnet'
      - value: 'nodejs'
        displayName: 'Node.js'
        logo: 'nodejs'
      - value: 'python'
        displayName: 'Python'
        logo: 'python'
      - value: 'ruby'
        displayName: 'Ruby'
        logo: 'ruby'

steps:
  - filePath: 'src/install/ai-monitoring/appInfo.mdx'
  - filePath: 'src/install/ai-monitoring/default.mdx' 
    overrides:
      - filePath: 'src/install/ai-monitoring/agent-lang/go-install.mdx'
        selectedOptions:
          - optionType: agent-lang
            options:
              - value: 'go'
      - filePath: 'src/install/ai-monitoring/agent-lang/go-install.mdx'
        selectedOptions:
          - optionType: agent-lang
            options:
              - value: 'go' 
      - filePath: 'src/install/ai-monitoring/agent-lang/python-jupyter-install.mdx'
        selectedOptions:
          - optionType: agent-lang
            options:
              - value: 'jupyter'
      - filePath: 'src/install/ai-monitoring/agent-lang/java-install.mdx'
        selectedOptions:
          - optionType: agent-lang
            options:
              - value: 'java'
      - filePath: 'src/install/ai-monitoring/agent-lang/dotnet-install.mdx'
        selectedOptions:
          - optionType: agent-lang
            options:
              - value: 'dotnet'
      - filePath: 'src/install/ai-monitoring/agent-lang/nodejs-install.mdx'
        selectedOptions:
          - optionType: agent-lang
            options:
              - value: 'nodejs'
      - filePath: 'src/install/ai-monitoring/agent-lang/python-install.mdx'
        selectedOptions:
          - optionType: agent-lang
            options:
              - value: 'python'  
      - filePath: 'src/install/ai-monitoring/agent-lang/ruby-install.mdx'
        selectedOptions:
          - optionType: agent-lang
            options:
              - value: 'ruby'   
  - filePath: 'src/install/ai-monitoring/agentConfigDefault.mdx'
    overrides:
      - filePath: 'src/install/ai-monitoring/agent-lang/go-config.mdx'
        selectedOptions:
          - optionType: agent-lang
            options:
              - value: 'go'
      - filePath: 'src/install/ai-monitoring/agent-lang/java-config.mdx'
        selectedOptions:
          - optionType: agent-lang
            options:
              - value: 'java'
      - filePath: 'src/install/ai-monitoring/agent-lang/python-jupyter-config.mdx'
        selectedOptions:
          - optionType: agent-lang
            options:
              - value: 'jupyter'  
      - filePath: 'src/install/ai-monitoring/agent-lang/dotnet-config.mdx'
        selectedOptions:
          - optionType: agent-lang
            options:
              - value: 'dotnet'
      - filePath: 'src/install/ai-monitoring/agent-lang/node-config.mdx'
        selectedOptions:
          - optionType: agent-lang
            options:
              - value: 'nodejs'
      - filePath: 'src/install/ai-monitoring/agent-lang/python-config.mdx'
        selectedOptions:
          - optionType: agent-lang
            options:
              - value: 'python'                
      - filePath: 'src/install/ai-monitoring/agent-lang/ruby-config.mdx'
        selectedOptions:
          - optionType: agent-lang
            options:
              - value: 'ruby'  
  - filePath: 'src/install/ai-monitoring/view-your-data.mdx'
whatsNextFilePath: 'src/install/ai-monitoring/whatsNext.mdx'
