agentName: android
agentType: integration
title: 'Install video agent for Android application'
metaDescription: 'Install the Streaming video & ads for Android application'
introFilePath: 'src/install/android/intro.mdx'
appInfo: 
  - optionType: task
    label: ''
    placeholder: 'Choose an option'
    options: 
      - value: 'EU'
        displayName: 'Instrument a new mobile application'
      - value: 'EA2'
        displayName: 'Instrument on mobile application you are already monitoring'

steps:
  - filePath: 'src/install/android/android-path/install_the_app.mdx'
  - filePath: 'src/install/android/appInfo.mdx'
  - filePath: 'src/install/android/android-path/appInfo_EU.mdx'
    overrides:
      - isConditionalStep: true      
        selectedOptions:
          - optionType: task
            options:
              - value: 'EU'
  - filePath: 'src/install/android/appInfo_EA2.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: task
            options:
              - value: 'EA2'                                             
whatsNextFilePath: 'src/install/android/whatsNext.mdx'