agentName: apache
agentType: integration
title: 'Apache monitoring integration'
metaDescription: 'Install the Apache integration'
introFilePath: 'src/install/apache/intro.mdx'
redirects:
  - /docs/integrations/host-integrations/host-integrations-list/apache-monitoring-integration
  - /docs/infrastructure/integrations/integrations/apache-integration-new-relic-infrastructure
  - /docs/apache-integration-new-relic-infrastructure
  - /docs/infrastructure/host-integrations/host-integrations-list/apache-monitoring-integration-new-relic-infrastructure
  - /docs/infrastructure/host-integrations/host-integrations-list/apache-monitoring-integration


# -----------------------------------------------------------------
# Create the buttons for the question you want to ask:
# -----------------------------------------------------------------
appInfo: 
  - optionType: deployment
    label: ""
    placeholder: "Choose one:"
    options:
      - value: "msi"
        displayName: "Install using MSI files (Windows)"
        logo: 'windows'
        recommendedGuided: true        
      - value: "apt"
        displayName: "Install using Apt (Debian, Ubuntu)"
        recommendedGuided: true        
      - value: "yum"
        logo: 'linux'      
        displayName: "Install using Yum (Amazon Linux, CentOS, RHEL)"
        recommendedGuided: true        
      - value: "zypper"
        displayName: "Install using Zypper (SLES)"
        recommendedGuided: true        
        logo: 'linux'        
      - value: "tar"
        displayName: "Install from tarball (Other Linux distros)"  
        recommendedGuided: true        
        logo: 'linux'                  

# ----------------------------------------------------
# Ask the first question and then provide instructions
# ----------------------------------------------------
steps:
  # Step 1: Ask the user what kind of deployment they want (not their OS)
  - filePath: 'src/install/apache/appInfo.mdx'

  # Step 2: Display the requirements
  - filePath: 'src/install/apache/default-requirements.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'apt'
              - value: 'msi'
              - value: 'tar'
              - value: 'yum'
              - value: 'zypper'
  # Step 3: Display the instructions to install the infra agent (prerequisite)
  - filePath: 'src/install/apache/install-infra.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'apt'
              - value: 'msi'
              - value: 'tar'
              - value: 'yum'
              - value: 'zypper'

  # ------------------------------
  # DISPLAY DEPLOYMENT INFORMATION
  # ------------------------------

  # Display download and installation for apt:
  - filePath: "src/install/apache/linux/install-apt.mdx"
    overrides:
      - isConditionalStep: true
        selectedOptions: 
        - optionType: deployment
          options: 
          - value: "apt"

  # Display download and installation for msi (Windows):
  - filePath: "src/install/apache/windows/install-msi.mdx"
    overrides:
      - isConditionalStep: true
        selectedOptions: 
        - optionType: deployment
          options: 
          - value: "msi" 

  # Display download and installation for tarball:
  - filePath: "src/install/apache/linux/install-tarball.mdx"
    overrides:
      - isConditionalStep: true
        selectedOptions: 
        - optionType: deployment
          options: 
          - value: "tar"

  # Display download and installation for yum:
  - filePath: "src/install/apache/linux/install-yum.mdx"
    overrides:
      - isConditionalStep: true
        selectedOptions: 
        - optionType: deployment
          options: 
          - value: "yum"

  # Display download and installation for zypper:        
  - filePath: "src/install/apache/linux/install-zypper.mdx"
    overrides:
      - isConditionalStep: true
        selectedOptions: 
        - optionType: deployment
          options: 
          - value: "zypper"

  # ------------------------------
  # DISPLAY CONFIGURATION OPTIONS
  # ------------------------------

  # Display Linux configuration options               
  - filePath: 'src/install/apache/default-configuration-linux.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'apt'
              - value: 'tar'
              - value: 'yum'
              - value: 'zypper'

  # Display msi (Windows) configuration options
  - filePath: 'src/install/apache/windows/configure-windows.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions: 
        - optionType: deployment
          options: 
          - value: "msi" 

  # ------------------------------
  # WRAP IT UP!!
  # ------------------------------

  # Display information about viewing your data    
  - filePath: 'src/install/apache/find-data.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'apt'
              - value: 'msi'
              - value: 'tar'
              - value: 'yum'
              - value: 'zypper'

whatsNextFilePath: 'src/install/apache/whatsNext.mdx'