agentName: aws-cloudwatch
agentType: integration
title: 'Amazon CloudWatch Metric Streams'
metaDescription: 'Install the Amazon CloudWatch Metric Streams integration'
introFilePath: 'src/install/aws-cloudwatch/intro.mdx'
redirects:
    - /docs/infrastructure/amazon-integrations/get-started/aws-metric-stream-setup
    - /docs/infrastructure/amazon-integrations/connect/cloudwatch-metric-streams/aws-metric-stream
    - /docs/infrastructure/amazon-integrations/connect/cloudwatch-metric-streams/aws-metric-stream-setup

#----------------------------------------------------------------
# Define the three methods for activating the integration:
#----------------------------------------------------------------

appInfo: 
  - optionType: task
    label: ''
    placeholder: 'Select one:'
    options: 
      - value: 'cloudformation'
        displayName: 'Use a Cloudformation template'
        logo: 'cloudformation'
      - value: 'console'
        displayName: 'Use AWS console'
        logo: 'console'
      - value: 'migrate'
        displayName: 'Migrate from API polling'
        logo: 'cloudwatch'

# ----------------------------------------------------
# Set-up changes the (default.mdx) step  based off the above choice
# ----------------------------------------------------


steps:
  # Users choose between CloudFormation, Console, or Migration
  - filePath: 'src/install/aws-cloudwatch/appInfo.mdx'
  # Permissions and region mapping. Same for all methods
  - filePath: 'src/install/aws-cloudwatch/permissions.mdx'
  # Procedures based on the user's choice
  - filePath: 'src/install/aws-cloudwatch/default.mdx'
    overrides: 
        - filePath: 'src/install/aws-cloudwatch/cloudwatch-path/cloudformation.mdx'
          selectedOptions: 
            - optionType: task
              options: 
                - value: 'cloudformation'
                # If CloudFormation, then these procedures
        - filePath: 'src/install/aws-cloudwatch/cloudwatch-path/console.mdx'
          selectedOptions: 
            - optionType: task
              options: 
                - value: 'console'
                # If AWS Console, then these procedures
        - filePath: 'src/install/aws-cloudwatch/cloudwatch-path/migrate.mdx'
          selectedOptions: 
            - optionType: task
              options: 
                - value: 'migrate'
                # If migrating from API polling, then these procedures
  - filePath: 'src/install/aws-cloudwatch/validate-data.mdx'
  # Validation steps. Same for all methods
whatsNextFilePath: 'src/install/aws-cloudwatch/whatsNext.mdx'
