agentName: aws-logs
agentType: integration
title: 'Forward AWS logs'
metaDescription: 'Forward logs from AWS'
introFilePath: 'src/install/aws-logs/intro.mdx'
redirects:
  - /docs/logs/enable-log-monitoring-new-relic/enable-log-monitoring-new-relic/aws-firelens-plugin-log-forwarding
  - /docs/logs/enable-log-monitoring-new-relic/enable-log-monitoring-new-relic/aws-firelens-plugin-logs
  - /docs/logs/enable-log-monitoring-new-relic/enable-log-monitoring-new-relic/aws-lambda-sending-cloudwatch-logs
  - /docs/logs/enable-logs/enable-logs/aws-cloudwatch-plugin-logs
  - /docs/logs/enable-logs/enable-logs/aws-firelens-plugin-logs
  - /docs/logs/forward-logs/aws-firelens-plugin-log-forwarding
  - /docs/logs/forward-logs/aws-lambda-sending-cloudwatch-logs
  - /docs/logs/new-relic-logs/enable-logs/enable-new-relic-logs-aws-cloudwatch
  - /docs/logs/new-relic-logs/enable-logs/enable-new-relic-logs-aws-firelens
  - /docs/logs/new-relic-logs/enable-logs/enable-new-relic-logs-aws-lambda
  - /docs/logs/new-relic-logs/enable-logs/enable-new-relic-logs-firelens
appInfo: 
  - optionType: service
    label: ''
    placeholder: 'What type of AWS service are you forwarding logs from?'
    options: 
      - value: 'EC2'
        displayName: 'Amazon EC2'
      - value: 'EKS'
        displayName: 'Amazon EKS'
      - value: 'ECS'
        displayName: 'Amazon ECS'        
      - value: 'security_lake'
        displayName: 'Amazon route 53 logs / VPC Flow logs / AWS Cloudtrail logs/ AWS Security Hub'   
      - value: 'other'
        displayName: 'Other log types'            
  - optionType: forward_EC2
    label: ''
    placeholder: 'How would you like to forward your EC2 logs?'
    options: 
      - value: 'infra_fluentbit'
        displayName: 'Infrastructure agent with Fluentbit'
      - value: 'cloud_lambda'
        displayName: 'Cloudwatch Lambda Function'
      - value: 'data_firehose'
        displayName: 'Kinesis Data Firehose'        
  - optionType: forward_EKS
    label: ''
    placeholder: 'How would you like to forward your EKS logs?'
    options: 
      - value: 'k8s_integration'
        displayName: 'Kubernetes integration'
      - value: 'cloud_lambda'
        displayName: 'Cloudwatch Lambda Function'
  - optionType: forward_ECS
    label: ''
    placeholder: 'How would you like to forward your ECS logs?'
    options: 
      - value: 'infra_fluentbit'
        displayName: 'Infrastructure agent with Fluentbit'
      - value: 'cloud_lambda'
        displayName: 'Cloudwatch Lambda Function' 
      - value: 'sidecar_firelens'                          
        displayName: 'Sidecar container with Firelens'
  - optionType: forward_Other
    label: ''
    placeholder: 'Select logs destination:'
    options: 
      - value: 'data_firehose'
        displayName: 'Kinesis Data Firehose'  
      - value: 'cloud_lambda'
        displayName: 'Cloudwatch Lambda Function'       
steps:
  - filePath: 'src/install/aws-logs/appInfo_service.mdx'
  - filePath: 'src/install/aws-logs/appInfo_EC2.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'EC2'
  - filePath: 'src/install/aws-logs/appInfo_EKS.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'EKS' 
  - filePath: 'src/install/aws-logs/appInfo_ECS.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'ECS'       
  - filePath: 'src/install/aws-logs/appInfo_Other.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'other'               
  - filePath: 'src/install/aws-logs/security_lake/intro_securitylake.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'security_lake'         
  - filePath: 'src/install/aws-logs/agent/basic-agent.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_ECS
            options:
              - value: 'infra_fluentbit'
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_EC2
            options:
              - value: 'infra_fluentbit'              
  - filePath: 'src/install/aws-logs/cloudwatch/basic-cloudwatch.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_EC2
            options:
              - value: 'cloud_lambda' 
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_EKS
            options:
              - value: 'cloud_lambda'    
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_ECS
            options:
              - value: 'cloud_lambda'   
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_Other
            options:
              - value: 'cloud_lambda'                                           
  - filePath: 'src/install/aws-logs/cloudwatch/cloudwatch-lambda.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_EC2
            options:
              - value: 'cloud_lambda' 
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_EKS
            options:
              - value: 'cloud_lambda'    
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_ECS
            options:
              - value: 'cloud_lambda'   
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_Other
            options:
              - value: 'cloud_lambda'   
  - filePath: 'src/install/aws-logs/cloudwatch/configure-retries.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_EC2
            options:
              - value: 'cloud_lambda' 
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_EKS
            options:
              - value: 'cloud_lambda'    
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_ECS
            options:
              - value: 'cloud_lambda'   
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_Other
            options:
              - value: 'cloud_lambda'   
  - filePath: 'src/install/aws-logs/cloudwatch/view-log-data.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_EC2
            options:
              - value: 'cloud_lambda' 
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_EKS
            options:
              - value: 'cloud_lambda'    
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_ECS
            options:
              - value: 'cloud_lambda'   
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_Other
            options:
              - value: 'cloud_lambda'                                               
  - filePath: 'src/install/aws-logs/firehose/basic-firehose.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_EC2
            options:
              - value: 'data_firehose' 
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_Other
            options:
              - value: 'data_firehose'      
  - filePath: 'src/install/aws-logs/firehose/firehose-eu.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_EC2
            options:
              - value: 'data_firehose' 
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_Other
            options:
              - value: 'data_firehose'                    
  - filePath: 'src/install/aws-logs/firehose/firehose-view.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_EC2
            options:
              - value: 'data_firehose' 
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_Other
            options:
              - value: 'data_firehose'                                             
  - filePath: 'src/install/aws-logs/k8s/basic-k8s.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_EKS
            options:
              - value: 'k8s_integration'        
  - filePath: 'src/install/aws-logs/firelens/basic-firelens.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_ECS
            options:
              - value: 'sidecar_firelens'        
  - filePath: 'src/install/aws-logs/firelens/firelens-configure.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_ECS
            options:
              - value: 'sidecar_firelens'   
  - filePath: 'src/install/aws-logs/firelens/firelens-eu.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_ECS
            options:
              - value: 'sidecar_firelens'  
  - filePath: 'src/install/aws-logs/firelens/firelens-view.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: forward_ECS
            options:
              - value: 'sidecar_firelens'                                                          
whatsNextFilePath: 'src/install/aws-logs/whatsNext.mdx'              