agentName: cassandra
agentType: integration
title: 'Cassandra monitoring integration'
metaDescription: 'Install the Cassandra integration'
introFilePath: 'src/install/cassandra/intro.mdx'
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your environment'
    options: 
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'
      - value: 'ecs'
        displayName: 'ECS'
        logo: 'amazonECS'
      - value: 'kubernetes'
        displayName: 'Kubernetes'
        logo: 'k8'
  - optionType: deployment
    label: "Choose your install path"
    placeholder: "Choose one:"
    options:     
      - value: "apt"
        displayName: "Install using Apt (Debian, Ubuntu)"
      - value: "yum"
        logo: 'linux'      
        displayName: "Install using Yum (Amazon Linux, CentOS, RHEL)"
      - value: "zypper"
        displayName: "Install using Zypper (SLES)"
      - value: "tar"
        displayName: "Install from tarball (Other Linux distros)"  
        logo: 'linux'  
steps:
  - filePath: 'src/install/cassandra/guided.mdx'
  - filePath: 'src/install/cassandra/default-requirements.mdx'
    overrides: 
        - filePath: 'src/install/cassandra/ecs/requirements-ecs.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'ecs'
        - filePath: 'src/install/cassandra/kubernetes/requirements-k8s.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'kubernetes'
        - filePath: 'src/install/cassandra/linux/requirements-linux.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'linux' 
  - filePath: 'src/install/cassandra/install-infra.mdx'
  - filePath: "src/install/cassandra/linux/install-apt.mdx"
    overrides: 
        - filePath: "src/install/cassandra/linux/install-apt.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "apt" 
        - filePath: "src/install/cassandra/linux/install-yum.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "yum"
        - filePath: "src/install/cassandra/linux/install-tarball.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "tar"
        - filePath: "src/install/cassandra/linux/install-zypper.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "zypper"
  - filePath: 'src/install/cassandra/linux/install-linux.mdx'
    overrides: 
        - filePath: 'src/install/cassandra/linux/install-linux.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'linux'
        - filePath: 'src/install/cassandra/ecs/install-ecs.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'ecs'
        - filePath: 'src/install/cassandra/kubernetes/install-k8s.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'kubernetes'  
  - filePath: 'src/install/cassandra/find-data.mdx'
whatsNextFilePath: 'src/install/cassandra/whatsNext.mdx'