agentName: demo
agentType: APM
title: 'A demo branching doc'
metaDescription: 'A demo branching doc for learning more about how this works.'
introFilePath: 'src/install/demo/intro.mdx'
agentConfigFilePath: 'src/install/config/agent-config/demo-config.txt'
appInfo:
  - optionType: dropdown1
    label: 'This is the first set of options'
    placeholder: 'Choose an option'
    options:
      - value: 'firstOption'
        displayName: 'First option'
        logo: 'appServer'
        recommendedGuided: true
      - value: 'secondOption'
        displayName: 'Second option'
        icon: 'book'
  - optionType: dropdown2
    label: 'This is the second set of options'
    placeholder: 'Choose another option'
    options:
      - value: 'thirdOption'
        displayName: 'Third option!'
        icon: 'box'
      - value: 'fourthOption'
        displayName: 'Fourth option'
        icon: 'database'

steps:
  - filePath: 'src/install/demo/appInfo.mdx'
  - filePath: 'src/install/demo/agentConfig.mdx'
  - filePath: 'src/install/demo/dropdown1/default.mdx'
    overrides:
      - filePath: 'src/install/demo/dropdown1/firstOption.mdx'
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'firstOption'
      - filePath: 'src/install/demo/dropdown1/secondOption.mdx'
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'secondOption'
  - filePath: 'src/install/demo/dropdown2/default.mdx'
    overrides:
      - filePath: 'src/install/demo/dropdown2/thirdOption.mdx'
        selectedOptions:
          - optionType: dropdown2
            options:
              - value: 'thirdOption'
      - skip: true
        selectedOptions:
          - optionType: dropdown2
            options:
              - value: 'fourthOption'
  - filePath: 'src/install/demo/dropdown2/addStep.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdown2
            options:
              - value: 'thirdOption'
whatsNextFilePath: 'src/install/demo/whatsNext.mdx'
