agentName: elastic
agentType: integration
title: 'Elasticsearch monitoring integration'
metaDescription: 'Install the Elasticsearch integration'
redirects:
  - /docs/infrastructure/amazon-integrations/aws-integrations-list/aws-elasticsearch-monitoring-integration
  - /docs/integrations/host-integrations/host-integrations-list/elasticsearch-monitoring-integration
  - /docs/elasticsearch-monitoring-integration
  - /docs/elasticsearchonhost-integration-new-relic-infrastructure
  - /docs/infrastructure/host-integrations/host-integrations-list/elasticsearch-monitoring-integration
  - /docs/infrastructure/host-integrations/host-integrations-list/elasticsearch/elasticsearch-config
introFilePath: 'src/install/elasticsearch/intro.mdx'
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your environment'
    options: 
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'
      - value: 'windows'
        displayName: 'Windows'
        logo: 'windows'
  - optionType: deployment
    label: "Choose your install path"
    placeholder: "Choose one:"
    options:
      - value: "msi"
        displayName: "Install using MSI files (Windows)"
        logo: 'windows'     
      - value: "apt"
        displayName: "Install using Apt (Debian, Ubuntu)"      
      - value: "yum"
        logo: 'linux'      
        displayName: "Install using Yum (Amazon Linux, CentOS, RHEL)" 
      - value: "zypper"
        displayName: "Install using Zypper (SLES)"    
        logo: 'linux'        
      - value: "tar"
        displayName: "Install from tarball (Other Linux distros)"        
        logo: 'linux'                  


steps:
  - filePath: 'src/install/elasticsearch/appInfo.mdx'
  - filePath: 'src/install/elasticsearch/install-infra.mdx'
  - filePath: "src/install/elasticsearch/linux/install-apt.mdx"
    overrides: 
        - filePath: "src/install/elasticsearch/linux/install-apt.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "apt"
        - filePath: "src/install/elasticsearch/linux/install-tarball.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "tar"
        - filePath: "src/install/elasticsearch/linux/install-yum.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "yum"
        - filePath: "src/install/elasticsearch/linux/install-zypper.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "zypper"
        - filePath: "src/install/elasticsearch/windows/install-msi.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "msi"                 
  - filePath: 'src/install/elasticsearch/default-install-linux.mdx'
    overrides: 
        - filePath: 'src/install/elasticsearch/linux/install-linux.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'linux'
        - filePath: 'src/install/elasticsearch/windows/install-windows.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'windows'         
  - filePath: 'src/install/elasticsearch/find-data.mdx'
whatsNextFilePath: 'src/install/elasticsearch/whatsNext.mdx'
