agentName: ibm-mq
agentType: integration
title: 'IBM MQ monitoring integration'
metaDescription: 'Install the IBM MQ integration'
introFilePath: 'src/install/ibm-mq/intro.mdx'
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your environment'
    options: 
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'
        recommendedGuided: true
      - value: 'windows'
        displayName: 'Windows'
        logo: 'windows'
        recommendedGuided: true
  - optionType: deployment
    label: "Choose your install path"
    placeholder: "Choose one:"
    options:
      - value: "msi"
        displayName: "Install using MSI files (Windows)"
        logo: 'windows'
        recommendedGuided: true        
      - value: "apt"
        displayName: "Install using Apt (Debian, Ubuntu)"
        recommendedGuided: true        
      - value: "yum"
        logo: 'linux'      
        displayName: "Install using Yum (Amazon Linux, CentOS, RHEL)"
        recommendedGuided: true        
      - value: "zypper"
        displayName: "Install using Zypper (SLES)"
        recommendedGuided: true        
        logo: 'linux'        
      - value: "tar"
        displayName: "Install from tarball (Other Linux distros)"  
        recommendedGuided: true        
        logo: 'linux'   
steps:
  - filePath: 'src/install/ibm-mq/appInfo.mdx'
  - filePath: 'src/install/ibm-mq/default-requirements.mdx'
    overrides: 
        - filePath: 'src/install/ibm-mq/linux/requirements-linux.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'linux'
        - filePath: 'src/install/ibm-mq/windows/requirements-windows.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'windows'  
  - filePath: 'src/install/ibm-mq/install-infra.mdx' 
  - filePath: "src/install/ibm-mq/linux/install-apt.mdx"
    overrides: 
        - filePath: "src/install/ibm-mq/linux/install-apt.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "apt"
        - filePath: "src/install/ibm-mq/linux/install-tarball.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "tar"
        - filePath: "src/install/ibm-mq/linux/install-yum.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "yum"
        - filePath: "src/install/ibm-mq/linux/install-zypper.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "zypper"
        - filePath: "src/install/ibm-mq/windows/install-msi.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "msi"  
  - filePath: 'src/install/ibm-mq/default-install.mdx'
    overrides: 
        - filePath: 'src/install/ibm-mq/linux/install-linux.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'linux'
        - filePath: 'src/install/ibm-mq/windows/install-windows.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'windows'    
  - filePath: 'src/install/ibm-mq/find-data.mdx'

whatsNextFilePath: 'src/install/ibm-mq/whatsNext.mdx'