agentName: kafka
agentType: integration
title: 'Kafka monitoring integration'
metaDescription: 'Install the Kafka integration'
redirects:
  - /docs/integrations/host-integrations/host-integrations-list/kafka-monitoring-integration
  - /docs/kafka-integration-new-relic-infrastructure
  - /docs/infrastructure/host-integrations/host-integrations-list/kafka-monitoring-integration
  - /docs/infrastructure/host-integrations/host-integrations-list/kafka/kafka-config
  - /docs/infrastructure/host-integrations/host-integrations-list/kafka/kafka-integration
introFilePath: 'src/install/kafka/intro.mdx'
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your environment'
    options: 
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'
        recommendedGuided: true
      - value: 'windows'
        displayName: 'Windows'
        logo: 'windows'
        recommendedGuided: true
  - optionType: deployment
    label: "Choose your install path"
    placeholder: "Choose one:"
    options:
      - value: "msi"
        displayName: "Install using MSI files (Windows)"
        logo: 'windows'
        recommendedGuided: true        
      - value: "apt"
        displayName: "Install using Apt (Debian, Ubuntu)"
        recommendedGuided: true        
      - value: "yum"
        logo: 'linux'      
        displayName: "Install using Yum (Amazon Linux, CentOS, RHEL)"
        recommendedGuided: true        
      - value: "zypper"
        displayName: "Install using Zypper (SLES)"
        recommendedGuided: true        
        logo: 'linux'        
      - value: "tar"
        displayName: "Install from tarball (Other Linux distros)"  
        recommendedGuided: true        
        logo: 'linux'        
  - optionType: autodiscovery
    label: "Choose your autodiscovery option"      
    placeholder: "Due to the distributed nature of Kafka, the number and list of brokers changes dynamically. For this reason, the Kafka integration offers two mechanisms to perform automatic discovery of the list of brokers in the cluster. The bootstrap option uses a defined bootstrap broker to obtain a list of brokers, while the Zookeeper option connects to a defined Zookeeper server in order to obtain the list of brokers. If you're unsure which option to choose, select Bootstrap."
    options:  
      - value: 'bootstrap'
        displayName: 'Bootstrap'
        recommendedGuided: true             
      - value: 'zookeeper'
        displayName: 'Zookeeper'
        recommendedGuided: true             


steps:
  - filePath: 'src/install/kafka/appInfo.mdx'
  - filePath: 'src/install/kafka/default-requirements.mdx'
  - filePath: 'src/install/kafka/install-infra.mdx'
  - filePath: "src/install/kafka/linux/install-apt.mdx"
    overrides: 
        - filePath: "src/install/kafka/linux/install-apt.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "apt"
        - filePath: "src/install/kafka/linux/install-tarball.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "tar"
        - filePath: "src/install/kafka/linux/install-yum.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "yum"
        - filePath: "src/install/kafka/linux/install-zypper.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "zypper"
        - filePath: "src/install/kafka/windows/install-msi.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "msi"                 
  - filePath: 'src/install/kafka/default-install-linux.mdx'
    overrides: 
        - filePath: 'src/install/kafka/linux/install-linux-boot.mdx'    
          isConditionalStep: true
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'linux'    
            - optionType: autodiscovery
              options: 
                - value: 'bootstrap' 
        - filePath: 'src/install/kafka/linux/install-linux-zoo.mdx'        
          isConditionalStep: true
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'linux'    
            - optionType: autodiscovery
              options: 
                - value: 'zookeeper'
        - filePath: 'src/install/kafka/windows/install-windows-boot.mdx'        
          isConditionalStep: true
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'windows'    
            - optionType: autodiscovery
              options: 
                - value: 'bootstrap'  
        - filePath: 'src/install/kafka/windows/install-windows-zoo.mdx'        
          isConditionalStep: true
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'windows'    
            - optionType: autodiscovery
              options: 
                - value: 'zookeeper'                            
  - filePath: 'src/install/kafka/find-data.mdx'
whatsNextFilePath: 'src/install/kafka/whatsNext.mdx'
