agentName: kafka
agentType: integration
title: 'Kafka monitoring integration'
metaDescription: 'Here are several ways to install the Kafka integration'
introFilePath: 'src/install/kafka/intro.mdx'
redirects:
  - /docs/integrations/host-integrations/host-integrations-list/kafka-monitoring-integration
  - /docs/kafka-integration-new-relic-infrastructure
  - /docs/infrastructure/host-integrations/host-integrations-list/kafka-monitoring-integration
  - /docs/infrastructure/host-integrations/host-integrations-list/kafka/kafka-config
  - /docs/infrastructure/host-integrations/host-integrations-list/kafka/kafka-integration


# -----------------------------------------------------------------
# Create the buttons for asking about the environment
# -----------------------------------------------------------------

appInfo:
  - optionType: deployment 
    label: ''
    placeholder: "Choose the option that best matches how you'll install the integration."
    options:
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'
      - value: 'windows'
        displayName: 'Windows'
        logo: 'windows'
      - value: 'ecs'
        displayName: 'ECS'
        logo: 'amazonECS'
      - value: 'kubernetes'
        displayName: 'Kubernetes'
        logo: 'k8'  

  - optionType: linux
    label: ''
    placeholder: "How would you like to enable your Linux environment?"
    options:
      - value: 'apt'
        displayName: 'Install using Apt (Debian, Ubuntu)'
      - value: 'yum'
        displayName: 'Install using Yum (Amazon Linux, CentOS, RHEL)'
      - value: 'zypper'
        displayName: 'Install using Zypper (SLES)'     
      - value: 'tar'
        displayName: 'Install from Tarball (Other Linux distros)'        


# -----------------------------------------------------------------
# These are the steps that must be followed
# -----------------------------------------------------------------
steps:

# This is the first step to select between Linux, Windows, ECS, and K8s
  - filePath: 'src/install/kafka/appInfo.mdx'

# -----------------------------------------------------------------
# If Linux is selected, this step loads.
# The user has to choose an option to enable the Linux environment
# -----------------------------------------------------------------

  - filePath: 'src/install/kafka/linux-yes.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'linux'  

# If ECS is selected, this step loads
  - filePath: 'src/install/kafka/ecs/install-ecs.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'ecs'

# If K8s is selected, this step loads
  - filePath: 'src/install/kafka/kubernetes/install-k8s.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'kubernetes'

# If Windows is selected, this step loads
  - filePath: 'src/install/kafka/windows/install-msi.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'windows'

# If Linux and APT is selected, this step loads
  - filePath: 'src/install/kafka/linux/install-apt.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: linux
            options:
              - value: 'apt'

# If Linux and Yum is selected, this step loads
  - filePath: 'src/install/kafka/linux/install-yum.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: linux
            options:
              - value: 'yum'

# If Linux and Zypper is selected, this step loads
  - filePath: 'src/install/kafka/linux/install-zypper.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: linux
            options:
              - value: 'zypper'

# If Linux and Tarball is selected, this step loads
  - filePath: 'src/install/kafka/linux/install-tarball.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: linux
            options:
              - value: 'tar'

# -----------------------------------------------------------------
# This step loads always you select an option except for ECS because
# the instructions for ECS include already the installation of the
# infrastructure agent.
# -----------------------------------------------------------------

  - filePath: 'src/install/kafka/install-infra.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'kubernetes'
      - isConditionalStep: true
        selectedOptions:              
          - optionType: linux
            options:
              - value: 'apt'
              - value: 'yum'
              - value: 'zypper'
              - value: 'tar'
      - isConditionalStep: true
        selectedOptions:              
          - optionType: deployment
            options:
              - value: 'windows'

# -----------------------------------------------------------------
# This step loads when one of these options: apt, yum, zypper, or tar
# has been selected. These are the instructions to configure Kafka.
# -----------------------------------------------------------------

  - filePath: 'src/install/kafka/linux/install-linux.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: linux
            options:
              - value: 'apt'
              - value: 'yum'
              - value: 'zypper'
              - value: 'tar'

# -----------------------------------------------------------------
# This step loads when Windows has been selected. 
# These are the instructions to configure Kafka.
# -----------------------------------------------------------------

  - filePath: 'src/install/kafka/windows/configure-windows.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'windows'

# -----------------------------------------------------------------
# This is the step for the find an use data. It loads with all options
# -----------------------------------------------------------------

  - filePath: 'src/install/kafka/find-data.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'kubernetes'
              - value: 'ecs'
              - value: 'windows'          
      - isConditionalStep: true
        selectedOptions:              
          - optionType: linux
            options:
              - value: 'apt'
              - value: 'yum'
              - value: 'zypper'
              - value: 'tar'

# -----------------------------------------------------------------
# This is not an step.
# This file includes all the configuration options, metrics, and 
# troubleshooting. It loads with all options
# -----------------------------------------------------------------

whatsNextFilePath: 'src/install/kafka/whatsNext.mdx'
