agentName: kubernetes
agentType: integration
title: 'Install the Kubernetes integration'
metaDescription: 'Install the Kubernetes integration'
redirects:
  - /docs/integrations/kubernetes-integration/installation/kubernetes-integration-install-configure
  - /docs/kubernetes-monitoring-integration-beta
  - /docs/kubernetes-integration-beta
  - /docs/kubernetes-integration
  - /docs/kubernetes-integration-new-relic-infrastructure
  - /docs/kubernetes-monitoring-integration
  - /docs/integrations/host-integrations/host-integrations-list/kubernetes-monitoring-integration
  - /docs/integrations/kubernetes-integration/installation/kubernetes-monitoring-integration
  - /docs/integrations/kubernetes-integration/installation/kubernetes-monitoring-installation
  - /docs/integrations/kubernetes-integration/installation/kubernetes-installation-configuration
  - /docs/integrations/kubernetes-integration/installation
  - /docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm/
  - /docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-install-configure
introFilePath: 'src/install/kubernetes/intro.mdx'
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: ''
    options: 
      - value: 'guided'
        displayName: 'Guided install'
        logo: 'nr-logo'
      - value: 'helm'
        displayName: 'Helm'
        logo: 'helm'
      - value: 'manifest'
        displayName: 'Manifest'
        logo: 'k8'
        
steps:
  - filePath: 'src/install/kubernetes/default-requirements.mdx'
  - filePath: 'src/install/kubernetes/prepare-install.mdx'  
  - filePath: 'src/install/kubernetes/appInfo.mdx'
  - filePath: "src/install/kubernetes/install.mdx"
    overrides: 
        - filePath: 'src/install/kubernetes/guided/install-guided.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'guided' 
        - filePath: 'src/install/kubernetes/helm/install-helm.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'helm' 
        - filePath: 'src/install/kubernetes/manifest/install-manifest.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'manifest'
  - filePath: 'src/install/kubernetes/helm/configuration-helm.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'helm'
  - filePath: 'src/install/kubernetes/manifest/configuration-manifest.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'manifest'
  - filePath: 'src/install/kubernetes/find-data.mdx'
whatsNextFilePath: 'src/install/kubernetes/whatsNext.mdx'