agentName: media-ios
agentType: integration
title: 'Install the video agent for iOS application'
metaDescription: 'Install the Streaming video & ads for iOS agent'
introFilePath: 'src/install/media-ios/intro.mdx'
appInfo: 
  - optionType: task
    label: ''
    placeholder: 'Choose an option'
    options: 
      - value: 'AI'
        displayName: 'Instrument a new mobile application'
      - value: 'EI2'
        displayName: 'Instrument a mobile application you are already monitoring'

steps:
  - filePath: 'src/install/media-ios/ios-path/install_the_app.mdx'
  - filePath: 'src/install/media-ios/appInfo.mdx'
  - filePath: 'src/install/media-ios/ios-path/appInfo_AC.mdx'
    overrides:
      - isConditionalStep: true      
        selectedOptions:
          - optionType: task
            options:
              - value: 'AI'
  - filePath: 'src/install/media-ios/appInfo_EB2.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: task
            options:
              - value: 'EI2'                                             
whatsNextFilePath: 'src/install/media-ios/whatsNext.mdx'