agentName: memcached
agentType: integration
title: 'Memcached monitoring integration'
metaDescription: 'Install the Memcached integration'
redirects:  
  - /docs/integrations/host-integrations/host-integrations-list/memcached-monitoring-integration
  - /docs/memcached-integration-new-relic-infrastructure
  - /docs/infrastructure/host-integrations/host-integrations-list/memcached-monitoring-integration
introFilePath: 'src/install/memcached/intro.mdx'
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your environment'
    options: 
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'
        recommendedGuided: true
      - value: 'windows'
        displayName: 'Windows'
        logo: 'windows'
        recommendedGuided: true
  - optionType: deployment
    label: "Choose your install path"
    placeholder: "Choose one:"
    options:
      - value: "msi"
        displayName: "Install using MSI files (Windows)"
        logo: 'windows'
        recommendedGuided: true        
      - value: "apt"
        displayName: "Install using Apt (Debian, Ubuntu)"
        recommendedGuided: true        
      - value: "yum"
        logo: 'linux'      
        displayName: "Install using Yum (Amazon Linux, CentOS, RHEL)"
        recommendedGuided: true        
      - value: "zypper"
        displayName: "Install using Zypper (SLES)"
        recommendedGuided: true        
        logo: 'linux'        
      - value: "tar"
        displayName: "Install from tarball (Other Linux distros)"  
        recommendedGuided: true        
        logo: 'linux'                  

steps:
  - filePath: 'src/install/memcached/appInfo.mdx'
  - filePath: 'src/install/memcached/default-requirements.mdx'
  - filePath: 'src/install/memcached/install-infra.mdx'
  - filePath: "src/install/memcached/linux/install-apt.mdx"
    overrides: 
        - filePath: "src/install/memcached/linux/install-apt.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "apt"
        - filePath: "src/install/memcached/linux/install-tarball.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "tar"
        - filePath: "src/install/memcached/linux/install-yum.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "yum"
        - filePath: "src/install/memcached/linux/install-zypper.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "zypper"
        - filePath: "src/install/memcached/windows/install-msi.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "msi"                   
  - filePath: 'src/install/memcached/default-install-linux.mdx'
    overrides: 
        - filePath: 'src/install/memcached/linux/install-linux.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'linux'
        - filePath: 'src/install/memcached/windows/install-windows.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'windows'         
  - filePath: 'src/install/memcached/find-data.mdx'
whatsNextFilePath: 'src/install/memcached/whatsNext.mdx'
