agentName: microsoft-sql
agentType: integration
title: 'Microsoft SQL monitoring integration'
metaDescription: 'Install the Microsoft SQL integration'
redirects:
  - /docs/integrations/host-integrations/host-integrations-list/microsoft-sql-server-monitoring-integration
  - /docs/mssql-integration-new-relic-infrastructure
  - /docs/integrations/host-integrations/host-integrations-list/mssql-monitoring-integration
  - /docs/mssql-monitoring-integration
  - /docs/infrastructure/host-integrations/host-integrations-list/microsoft-sql-server-monitoring-integration
  - /docs/infrastructure/host-integrations/host-integrations-list/microsoft-sql/microsoft-sql-server-integration
  - /docs/infrastructure/host-integrations/host-integrations-list/microsoft-sql/microsoft-sql-server-query-performance
introFilePath: 'src/install/microsoft-sql/intro.mdx'
appInfo: 
  - optionType: environment # Select the environment 
    label: ''
    placeholder: 'Select your environment'
    options: 
      - value: 'windows'
        displayName: 'Windows'
        logo: 'windows'
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'
  - optionType: windows  # Select the installation method for windows
    label: "Select the installation method"
    placeholder: "Choose one:"
    options:
      - value: "guided"    
        displayName: "Guided"  
      - value: "manual"    
        displayName: "Manual"
  - optionType: linux  # Select the installation method for linux
    label: "Select the installation method"
    placeholder: "Choose one:"
    options:
      - value: "apt"
        displayName: "Install using Apt (Debian, Ubuntu)"        
      - value: "yum"
        logo: 'linux'      
        displayName: "Install using Yum (Amazon Linux, CentOS, RHEL)"       
      - value: "zypper"
        displayName: "Install using Zypper (SLES)"
        logo: 'linux'
  - optionType: authentication
    label: ""
    placeholder: "Select how you'll enable your SQL server integration:" # This optionType is used to select the authentication method
    options:    
      - value: "sql"
        displayName: "SQL"   
      - value: "windows-domain"
        displayName: "Windows domain"
      - value: "gmsa"
        displayName: "Microsoft Group Managed Service Account (gMSA)"
      - value: "entra-id-service-principal"
        displayName: "EntraId Service Principal"
  # - optionType: deployment
  #   label: "Choose your install path"
  #   placeholder: "Choose one:"
  #   options:
  #     - value: "msi"
  #       displayName: "Install using MSI files (Windows)"
  #       logo: 'windows'
  #       recommendedGuided: true        
  #     - value: "apt"
  #       displayName: "Install using Apt (Debian, Ubuntu)"
  #       recommendedGuided: true        
  #     - value: "yum"
  #       logo: 'linux'      
  #       displayName: "Install using Yum (Amazon Linux, CentOS, RHEL)"
  #       recommendedGuided: true        
  #     - value: "zypper"
  #       displayName: "Install using Zypper (SLES)"
  #       recommendedGuided: true        
  #       logo: 'linux'              

steps:
  - filePath: 'src/install/microsoft-sql/appInfo_env.mdx'
  - filePath: 'src/install/microsoft-sql/appInfo_windows.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: environment
            options:
              - value: 'windows'
  - filePath: 'src/install/microsoft-sql/appInfo_linux.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: environment
            options:
              - value: 'linux'
  - filePath: 'src/install/microsoft-sql/appInfo_auth.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: windows
            options:
              - value: 'manual'
  # - filePath: 'src/install/microsoft-sql/appInfo.mdx'
  - filePath: 'src/install/microsoft-sql/windows/requirements-sql.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions: 
          - optionType: authentication
            options: 
              - value: "sql"
  - filePath: 'src/install/microsoft-sql/windows/requirements.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions: 
          - optionType: authentication
            options: 
              - value: "windows-domain"
      - isConditionalStep: true
        selectedOptions: 
          - optionType: authentication
            options: 
              - value: "gmsa"
  - filePath: 'src/install/microsoft-sql/windows/requirements-entra-id-service-principal.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions: 
          - optionType: authentication
            options: 
              - value: "entra-id-service-principal"
  - filePath: 'src/install/microsoft-sql/linux/requirements.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions: 
          - optionType: linux
            options: 
              - value: "zypper"
      - isConditionalStep: true
        selectedOptions: 
          - optionType: linux
            options: 
              - value: "apt"
      - isConditionalStep: true
        selectedOptions: 
          - optionType: linux
            options: 
              - value: "yum"  
  - filePath: 'src/install/microsoft-sql/install-infra.mdx' 
    overrides:
      - isConditionalStep: true
        selectedOptions: 
          - optionType: authentication
            options: 
              - value: "sql"
      - isConditionalStep: true
        selectedOptions: 
          - optionType: authentication
            options: 
              - value: "windows-domain"
      - isConditionalStep: true
        selectedOptions: 
          - optionType: authentication
            options: 
              - value: "gmsa"
      - isConditionalStep: true
        selectedOptions: 
          - optionType: authentication
            options: 
              - value: "entra-id-service-principal"
      - isConditionalStep: true
        selectedOptions: 
          - optionType: linux
            options: 
              - value: "zypper"
      - isConditionalStep: true
        selectedOptions: 
          - optionType: linux
            options: 
              - value: "apt"
      - isConditionalStep: true
        selectedOptions: 
          - optionType: linux
            options: 
              - value: "yum"  
  - filePath: "src/install/microsoft-sql/linux/install-apt.mdx"
    overrides:
      - isConditionalStep: true
        selectedOptions: 
          - optionType: linux
            options: 
              - value: "apt"
  - filePath: "src/install/microsoft-sql/linux/install-yum.mdx"
    overrides:
      - isConditionalStep: true
        selectedOptions: 
          - optionType: linux
            options: 
              - value: "yum"
  - filePath: "src/install/microsoft-sql/linux/install-zypper.mdx"
    overrides:
      - isConditionalStep: true
        selectedOptions: 
          - optionType: linux
            options: 
              - value: "zypper"
  - filePath: "src/install/microsoft-sql/windows/install-msi.mdx"
    overrides:
      - isConditionalStep: true
        selectedOptions: 
          - optionType: authentication
            options: 
              - value: "sql"
      - isConditionalStep: true
        selectedOptions: 
          - optionType: authentication
            options: 
              - value: "windows-domain"
      - isConditionalStep: true
        selectedOptions: 
          - optionType: authentication
            options: 
              - value: "gmsa"
      - isConditionalStep: true
        selectedOptions: 
          - optionType: authentication
            options: 
              - value: "entra-id-service-principal"
  - filePath: "src/install/microsoft-sql/windows/guided.mdx"
    overrides:
      - isConditionalStep: true
        selectedOptions: 
          - optionType: windows
            options: 
              - value: "guided"
  # - filePath: 'src/install/microsoft-sql/enable/default.mdx'
  #   overrides:
  #     - isConditionalStep: true
  #       selectedOptions: 
  #         - optionType: windows
  #           options: 
  #             - value: "manual"
  #     - isConditionalStep: true
  #       selectedOptions: 
  #         - optionType: environment
  #           options: 
  #             - value: "linux"
  - filePath: 'src/install/microsoft-sql/enable/sql.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions: 
          - optionType: authentication
            options: 
              - value: 'sql'      
  - filePath: 'src/install/microsoft-sql/enable/windows-domain.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions: 
          - optionType: authentication
            options: 
              - value: 'windows-domain'           
  - filePath: 'src/install/microsoft-sql/enable/gmsa.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions: 
          - optionType: authentication
            options: 
              - value: 'gmsa'
  - filePath: 'src/install/microsoft-sql/enable/entra-id-service-principal.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions: 
          - optionType: authentication
            options: 
              - value: 'entra-id-service-principal'               
  - filePath: 'src/install/microsoft-sql/windows/query.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions: 
          - optionType: authentication
            options: 
              - value: 'sql'
  - filePath: 'src/install/microsoft-sql/windows/query-level-monitoring-entra-id-service-principal.mdx'
    overrides:  
      - isConditionalStep: true
        selectedOptions: 
          - optionType: authentication
            options: 
              - value: "entra-id-service-principal"
  # - filePath: 'src/install/microsoft-sql/configure.mdx'
  #   overrides:
  #     - isConditionalStep: true
  #       selectedOptions: 
  #         - optionType: linux
  #           options: 
  #             - value: "apt"
  #     - isConditionalStep: true
  #       selectedOptions: 
  #         - optionType: linux
  #           options: 
  #             - value: "yum"
  #     - isConditionalStep: true
  #       selectedOptions: 
  #         - optionType: linux
  #           options: 
  #             - value: "zypper"
  #     - isConditionalStep: true
  #       selectedOptions:
  #         - optionType: windows
  #           options:
  #             - value: 'manual'
  - filePath: 'src/install/microsoft-sql/find-data.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions: 
          - optionType: authentication
            options: 
              - value: "sql"
      - isConditionalStep: true
        selectedOptions: 
          - optionType: authentication
            options: 
              - value: "windows-domain"
      - isConditionalStep: true
        selectedOptions: 
          - optionType: authentication
            options: 
              - value: "gmsa"
      - isConditionalStep: true
        selectedOptions: 
          - optionType: authentication
            options: 
              - value: "entra-id-service-principal"
      - isConditionalStep: true
        selectedOptions: 
          - optionType: linux
            options: 
              - value: "zypper"
      - isConditionalStep: true
        selectedOptions: 
          - optionType: linux
            options: 
              - value: "apt"
      - isConditionalStep: true
        selectedOptions: 
          - optionType: linux
            options: 
              - value: "yum"          

whatsNextFilePath: 'src/install/microsoft-sql/whatsNext.mdx'
