agentName: microsoft-sql
agentType: integration
title: 'Microsoft SQL monitoring integration'
metaDescription: 'Install the Microsoft SQL integration'
redirects:
  - /docs/integrations/host-integrations/host-integrations-list/microsoft-sql-server-monitoring-integration
  - /docs/mssql-integration-new-relic-infrastructure
  - /docs/integrations/host-integrations/host-integrations-list/mssql-monitoring-integration
  - /docs/mssql-monitoring-integration
  - /docs/infrastructure/host-integrations/host-integrations-list/microsoft-sql-server-monitoring-integration
  - /docs/infrastructure/host-integrations/host-integrations-list/microsoft-sql/microsoft-sql-server-integration
introFilePath: 'src/install/microsoft-sql/intro.mdx'
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your environment'
    options: 
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'
        recommendedGuided: true
      - value: 'windows'
        displayName: 'Windows'
        logo: 'windows'
        recommendedGuided: true
  - optionType: deployment
    label: "Choose your install path"
    placeholder: "Choose one:"
    options:
      - value: "msi"
        displayName: "Install using MSI files (Windows)"
        logo: 'windows'
        recommendedGuided: true        
      - value: "apt"
        displayName: "Install using Apt (Debian, Ubuntu)"
        recommendedGuided: true        
      - value: "yum"
        logo: 'linux'      
        displayName: "Install using Yum (Amazon Linux, CentOS, RHEL)"
        recommendedGuided: true        
      - value: "zypper"
        displayName: "Install using Zypper (SLES)"
        recommendedGuided: true        
        logo: 'linux'               
  - optionType: enable
    label: "Choose how you'll enable your SQL server"
    placeholder: "Choose one:"
    options:    
      - value: "SQL"
        displayName: "SQL"
        recommendedGuided: true      
      - value: "Windows domain"
        displayName: "windows-domain"
        recommendedGuided: true               
steps:
  - filePath: 'src/install/microsoft-sql/appInfo.mdx'
  - filePath: 'src/install/microsoft-sql/default-requirements.mdx'
  - filePath: 'src/install/microsoft-sql/install-infra.mdx' 
  - filePath: "src/install/microsoft-sql/linux/install-apt.mdx"
    overrides: 
        - filePath: "src/install/microsoft-sql/linux/install-apt.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "apt"
        - filePath: "src/install/microsoft-sql/linux/install-yum.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "yum"
        - filePath: "src/install/microsoft-sql/linux/install-zypper.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "zypper"
        - filePath: "src/install/microsoft-sql/windows/install-msi.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "msi"  
  - filePath: 'src/install/microsoft-sql/default-install.mdx'
    overrides: 
        - filePath: 'src/install/microsoft-sql/linux/install-linux.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'linux'
        - filePath: 'src/install/microsoft-sql/windows/install-windows.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'windows'   
  - filePath: 'src/install/microsoft-sql/enable/default.mdx'
    overrides: 
        - filePath: 'src/install/microsoft-sql/enable/sql.mdx'
          selectedOptions: 
            - optionType: enable
              options: 
                - value: 'sql'
        - filePath: 'src/install/microsoft-sql/enable/windows-domain.mdx'
          selectedOptions: 
            - optionType: enable
              options: 
                - value: 'windows-domain'                   
  - filePath: 'src/install/microsoft-sql/find-data.mdx'

whatsNextFilePath: 'src/install/microsoft-sql/whatsNext.mdx'