agentName: mongodb
agentType: integration
title: 'MongoDB monitoring integration'
metaDescription: 'Install the mongoDB integration'
introFilePath: 'src/install/mongodb/intro.mdx'
redirects:
    - /docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new
    - /docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration

# -----------------------------------------------------------------
# Create the buttons for asking about the environment
# -----------------------------------------------------------------

appInfo:
  - optionType: deployment 
    label: ''
    placeholder: "Choose the option that best matches how you'll install the integration"
    options:
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'
      - value: 'windows'
        displayName: 'Windows'
        logo: 'windows'
      - value: 'containerized'
        displayName: 'Containerized environments'

  - optionType: linux
    label: ''
    placeholder: "How would you like to enable your Linux environment?"
    options:
      - value: 'apt'
        displayName: 'Install using Apt (Debian, Ubuntu)'
      - value: 'yum'
        displayName: 'Install using Yum (Amazon Linux, CentOS, RHEL)'
      - value: 'zypper'
        displayName: 'Install using Zypper (SLES)'     
      - value: 'tar'
        displayName: 'Install from Tarball (Other Linux distros)'

  - optionType: hosted
    label: ''      
    placeholder: 'Choose one:'
    options:  
      - value: 'percona'
        displayName: 'Hosted MongoDB or Percona servers'           
      - value: 'atlas'
        displayName: 'Atlas'       


# -----------------------------------------------------------------
# These are the steps that must be followed
# -----------------------------------------------------------------

steps:

# This is the first step to select between Linux and Windows
  - filePath: 'src/install/mongodb/appInfo.mdx'

# -----------------------------------------------------------------
# If Linux is selected, this step loads.
# The user has to choose an option to enable the Linux environment
# -----------------------------------------------------------------

  - filePath: 'src/install/mongodb/linux-yes.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'linux'

# This is the step to select between Hosted MongoDB or Percona and Atlas
  - filePath: 'src/install/mongodb/database-hosted.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:              
          - optionType: linux
            options:
              - value: 'apt'
              - value: 'yum'
              - value: 'zypper'
              - value: 'tar'
      - isConditionalStep: true
        selectedOptions:              
          - optionType: deployment
            options:
              - value: 'windows'
              - value: 'containerized'

# If Windows is selected, this step loads
  - filePath: 'src/install/mongodb/windows/install-msi.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'windows'

# If K8s is selected, this step loads
  - filePath: 'src/install/mongodb/containerized-environments/containerized.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'containerized'    

# If Linux and APT is selected, this step loads
  - filePath: 'src/install/mongodb/linux/install-apt.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: linux
            options:
              - value: 'apt'

# If Linux and Yum is selected, this step loads
  - filePath: 'src/install/mongodb/linux/install-yum.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: linux
            options:
              - value: 'yum'

# If Linux and Zypper is selected, this step loads
  - filePath: 'src/install/mongodb/linux/install-zypper.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: linux
            options:
              - value: 'zypper'

# If Linux and Tarball is selected, this step loads
  - filePath: 'src/install/mongodb/linux/install-tarball.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: linux
            options:
              - value: 'tar'

# -----------------------------------------------------------------
# This step loads always, no matter which option you've selected
# -----------------------------------------------------------------
  - filePath: 'src/install/mongodb/install-infra.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:              
          - optionType: linux
            options:
              - value: 'apt'
              - value: 'yum'
              - value: 'zypper'
              - value: 'tar'
      - isConditionalStep: true
        selectedOptions:              
          - optionType: deployment
            options:
              - value: 'windows'
      - isConditionalStep: true
        selectedOptions:              
          - optionType: hosted
            options:
              - value: 'percona'
              - value: 'atlas'


# -----------------------------------------------------------------
# This step loads when MongoDB or Percona option has been selected. 
# -----------------------------------------------------------------
  - filePath: 'src/install/mongodb/host/percona.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: hosted
            options:
              - value: 'percona'

# -----------------------------------------------------------------
# This step loads when Atlas option has been selected. 
# -----------------------------------------------------------------
  - filePath: 'src/install/mongodb/host/atlas.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: hosted
            options:
              - value: 'atlas'


# -----------------------------------------------------------------
# This step loads when one of these options: apt, yum, zypper, or tar
# has been selected. These are the instructions to configure MongoDB.
# -----------------------------------------------------------------

  - filePath: 'src/install/mongodb/linux/install-linux.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: linux
            options:
              - value: 'apt'
              - value: 'yum'
              - value: 'zypper'
              - value: 'tar'

# -----------------------------------------------------------------
# This step loads when Windows has been selected. 
# These are the instructions to configure MongoDB.
# -----------------------------------------------------------------
  - filePath: 'src/install/mongodb/windows/configure-windows.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'windows'

# -----------------------------------------------------------------
# This is the step for the find an use data. It loads with all options
# -----------------------------------------------------------------
  - filePath: 'src/install/mongodb/find-data.mdx'
    overrides:     
      - isConditionalStep: true
        selectedOptions:              
          - optionType: linux
            options:
              - value: 'apt'
              - value: 'yum'
              - value: 'zypper'
              - value: 'tar'
      - isConditionalStep: true
        selectedOptions:              
          - optionType: deployment
            options:             
              - value: 'windows'
              - value: 'containerized'
      - isConditionalStep: true
        selectedOptions:              
          - optionType: hosted
            options:
              - value: 'percona'
              - value: 'atlas'

# -----------------------------------------------------------------
# This is not an step.
# This file includes all the configuration options, metrics, and 
# troubleshooting. It loads with all options
# -----------------------------------------------------------------
whatsNextFilePath: 'src/install/mongodb/whatsNext.mdx'
