agentName: mongodb
agentType: integration
title: 'MongoDB monitoring integration'
metaDescription: 'Install the mongoDB integration'
introFilePath: 'src/install/mongodb/intro.mdx'
redirects:
    - /docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new
    - /docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-migration-guide
    - /docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your environment'
    options: 
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'
        recommendedGuided: true
      - value: 'windows'
        displayName: 'Windows'
        logo: 'windows'
        recommendedGuided: true
  - optionType: deployment
    label: "Choose your install path"
    placeholder: "Choose one:"
    options:
      - value: "msi"
        displayName: "Install using MSI files (Windows)"
        logo: 'windows'
        recommendedGuided: true        
      - value: "apt"
        displayName: "Install using Apt (Debian, Ubuntu)"
        recommendedGuided: true        
      - value: "yum"
        logo: 'linux'      
        displayName: "Install using Yum (Amazon Linux, CentOS, RHEL)"
        recommendedGuided: true        
      - value: "zypper"
        displayName: "Install using Zypper (SLES)"
        recommendedGuided: true        
        logo: 'linux'        
      - value: "tar"
        displayName: "Install from tarball (Other Linux distros)"  
        recommendedGuided: true        
        logo: 'linux'        
  - optionType: hosted
    label: "How is your database hosted"      
    placeholder: 'Choose one:'
    options:  
      - value: 'percona'
        displayName: 'Hosted MongoDB or Percona servers'
        recommendedGuided: true             
      - value: 'atlas'
        displayName: 'Atlas'
        recommendedGuided: true             


steps:
  - filePath: 'src/install/mongodb/appInfo.mdx'
  - filePath: 'src/install/mongodb/default-requirements.mdx'
  - filePath: 'src/install/mongodb/install-infra.mdx'
  - filePath: "src/install/mongodb/linux/install-apt.mdx"
    overrides: 
        - filePath: "src/install/mongodb/linux/install-apt.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "apt"
        - filePath: "src/install/mongodb/linux/install-tarball.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "tar"
        - filePath: "src/install/mongodb/linux/install-yum.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "yum"
        - filePath: "src/install/mongodb/linux/install-zypper.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "zypper"
        - filePath: "src/install/mongodb/windows/install-msi.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "msi"  
  - filePath: 'src/install/mongodb/host/percona.mdx'
    overrides:  
        - filePath: 'src/install/mongodb/host/percona.mdx'
          selectedOptions:
            - optionType: hosted
              options:
                - value: 'percona'
        - filePath: 'src/install/mongodb/host/atlas.mdx'
          selectedOptions:
            - optionType: hosted
              options:
                - value: 'atlas'                  
  - filePath: 'src/install/mongodb/default-install-linux.mdx'
    overrides: 
        - filePath: 'src/install/mongodb/linux/install-linux.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'linux'
        - filePath: 'src/install/mongodb/windows/install-windows.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'windows'         
  - filePath: 'src/install/mongodb/find-data.mdx'
whatsNextFilePath: 'src/install/mongodb/whatsNext.mdx'
