agentName: mysql
agentType: integration
title: 'MySQL monitoring integration'
metaDescription: 'Install the MySQL integration'
introFilePath: 'src/install/mysql/intro.mdx'
redirects:
  - /docs/integrations/host-integrations/host-integrations-list/mysql-monitoring-integration
  - /docs/infrastructure/integrations/mysql-integration
  - /docs/infrastructure/integrations/mysql-integration-new-relic-infrastructure
  - /docs/infrastructure/integrations/integrations/mysql-integration-new-relic-infrastructure
  - /docs/mysql-integration-new-relic-infrastructure
  - /docs/infrastructure/host-integrations/host-integrations-list/mysql-monitoring-integration-new-relic-infrastructure
  - /docs/infrastructure/host-integrations/host-integrations-list/mysql-monitoring-integration
  - /docs/infrastructure/host-integrations/host-integrations-list/mySQL/mysql-integration
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your environment'
    options: 
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'
        recommendedGuided: true
      - value: 'windows'
        displayName: 'Windows'
        logo: 'windows'
      - value: 'k8'
        displayName: 'Kubernetes'
        logo: 'k8'
      - value: 'ecs'
        displayName: 'Amazon ECS'
        logo: 'amazonECS'

steps:
  - filePath: 'src/install/mysql/appInfo.mdx'
  - filePath: 'src/install/mysql/default-requirements.mdx'
    overrides: 
      - filePath: 'src/install/mysql/requirements-k8.mdx'
        selectedOptions: 
          - optionType: dropdown1
            options: 
              - value: 'k8'
      - filePath: 'src/install/mysql/requirements-amazonECS.mdx'
        selectedOptions: 
          - optionType: dropdown1
            options: 
              - value: 'ecs'
  - filePath: 'src/install/mysql/enable-mysql-server.mdx'
  - filePath: 'src/install/mysql/default-install-linux.mdx'
    overrides: 
        - filePath: 'src/install/mysql/linux/install-linux.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'linux'
        - filePath: 'src/install/mysql/windows/install-windows.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'windows'
        - filePath: 'src/install/mysql/k8/install-k8.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'k8'
        - filePath: 'src/install/mysql/amazonECS/install-amazonECS.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'ecs'
  - filePath: 'src/install/mysql/default-configuration.mdx'
    overrides: 
      - filePath: 'src/install/mysql/configure-mysql.mdx'
        selectedOptions: 
          - optionType: dropdown1
            options: 
              - value: 'linux'
              - value: 'windows'
      - skip: true
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'k8'
              - value: 'ecs'
  - filePath: 'src/install/mysql/find-data.mdx'
  - filePath: 'src/install/mysql/update-integration.mdx'
    overrides:
      - filePath: 'src/install/mysql/k8/update-integration-k8.mdx'
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'k8'
      - skip: true
        selectedOptions:
          - optionType: dropdown1
            options:
              - value: 'ecs'
whatsNextFilePath: 'src/install/mysql/whatsNext.mdx'
