agentName: mysql
agentType: integration
title: 'MySQL monitoring integration'
metaDescription: 'Install the MySQL integration'
introFilePath: 'src/install/mysql/intro.mdx'
redirects:
  - /docs/integrations/host-integrations/host-integrations-list/mysql-monitoring-integration
  - /docs/infrastructure/integrations/mysql-integration
  - /docs/infrastructure/integrations/mysql-integration-new-relic-infrastructure
  - /docs/infrastructure/integrations/integrations/mysql-integration-new-relic-infrastructure
  - /docs/mysql-integration-new-relic-infrastructure
  - /docs/infrastructure/host-integrations/host-integrations-list/mysql-monitoring-integration-new-relic-infrastructure
  - /docs/infrastructure/host-integrations/host-integrations-list/mysql-monitoring-integration
  - /docs/infrastructure/host-integrations/host-integrations-list/mysql-config
appInfo: 
  - optionType: environment # Select your environment
    label: ''
    placeholder: 'Select your environment'
    options: 
      - value: 'linux'
        displayName: 'Linux'
      - value: 'windows'
        displayName: 'Windows'
      - value: 'k8'
        displayName: 'Kubernetes'
      - value: 'ecs'
        displayName: 'Amazon ECS'
  - optionType: windows  # Select the installation method for windows
    label: "Select the installation method"
    placeholder: "Choose one:"
    options:
      - value: "guided"    
        displayName: "Guided"  
      - value: "manual"    
        displayName: "Manual"
  - optionType: linux  # Select the installation method for linux
    label: "Select the installation method"
    placeholder: "Choose one:"
    options:
      - value: "guided"    
        displayName: "Guided"  
      - value: "manual"    
        displayName: "Manual"
  # - optionType: kubernetes  # Select the installation method for Kubernetes
  #   label: "Select the installation method"
  #   placeholder: "Choose one:"
  #   options:
  #     - value: "guided"    
  #       displayName: "Guided"  
  #     - value: "manual"    
  #       displayName: "Manual"
  # - optionType: apt_deployment
  #   label: "Choose your OS"
  #   placeholder: "Choose one:"
  #   options:  
  #     - value: "apt"    
  #       displayName: "(Debian, Ubuntu)"       
  #     - value: "yum"  
  #       displayName: "(Amazon Linux, CentOS, RHEL, Oracle Linux)"
  - optionType: yum_deployment  # Select the OS for query monitoring
    label: "Choose your OS"
    placeholder: "Choose one:"
    options:  
      - value: "apt"    
        displayName: "(Debian, Ubuntu)"       
      - value: "yum"  
        displayName: "(Amazon Linux, CentOS, RHEL, Oracle Linux)"

steps:
  - filePath: 'src/install/mysql/appInfo_env.mdx'
  - filePath: 'src/install/mysql/appInfo_linux.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: environment
            options:
              - value: 'linux'
  # - filePath: 'src/install/mysql/appInfo_kubernetes.mdx'
  #   overrides:
  #     - isConditionalStep: true
  #       selectedOptions:
  #         - optionType: environment
  #           options:
  #             - value: 'k8'
  - filePath: 'src/install/mysql/appInfo_windows.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: environment
            options:
              - value: 'windows' 
  - filePath: 'src/install/mysql/linux/requirements.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: linux
            options:
              - value: 'guided' 
  - filePath: 'src/install/mysql/linux/requirements.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: linux
            options:
              - value: 'manual'
  - filePath: 'src/install/mysql/windows/requirements-win.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: windows
            options:
              - value: 'guided' 
  - filePath: 'src/install/mysql/windows/requirements-win.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: windows
            options: 
              - value: 'manual'
  # - filePath: 'src/install/mysql/k8/requirements-k8.mdx'
  #   overrides:
  #     - isConditionalStep: true
  #       selectedOptions:
  #         - optionType: kubernetes
  #           options: 
  #             - value: 'guided'
  # - filePath: 'src/install/mysql/k8/guided.mdx'
  #   overrides:
  #     - isConditionalStep: true
  #       selectedOptions:
  #         - optionType: kubernetes
  #           options:
  #             - value: 'guided' 
  - filePath: 'src/install/mysql/k8/requirements-k8.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: environment
            options: 
              - value: 'k8'
  - filePath: 'src/install/mysql/k8/install-k8.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: environment
            options: 
              - value: 'k8'
  - filePath: 'src/install/mysql/amazonECS/requirements-amazonECS.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: environment
            options:
              - value: 'ecs' 
  - filePath: 'src/install/mysql/amazonECS/install-amazonECS.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: environment
            options:
              - value: 'ecs' 
  - filePath: 'src/install/mysql/linux/guided.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: linux
            options:
              - value: 'guided' 
  - filePath: 'src/install/mysql/windows/guided.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions: 
          - optionType: windows
            options:
              - value: 'guided' 
  - filePath: 'src/install/mysql/k8s/guided.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: kubernetes
            options:
              - value: 'guided' 
  - filePath: 'src/install/mysql/linux/default-install-linux.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: linux
            options:
              - value: 'manual' 
  - filePath: 'src/install/mysql/linux/configure-mysql.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: linux
            options:
              - value: 'manual' 
  - filePath: 'src/install/mysql/linux/enable-mysql-server.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: linux
            options:
              - value: 'manual' 
  - filePath: 'src/install/mysql/appInfo_yum.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: linux
            options:
              - value: 'manual'
  - filePath: 'src/install/mysql/linux/update-config-apt.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: yum_deployment
            options:
              - value: 'apt' 
  - filePath: 'src/install/mysql/linux/update-config-yum.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: yum_deployment
            options:
              - value: 'yum' 
  - filePath: 'src/install/mysql/find-data.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: yum_deployment
            options:
              - value: 'apt' 
  - filePath: 'src/install/mysql/find-data.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: yum_deployment
            options:
              - value: 'yum' 
  - filePath: 'src/install/mysql/windows/install-windows.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: windows
            options:
              - value: 'manual' 
  - filePath: 'src/install/mysql/windows/configure-mysql.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: windows
            options:
              - value: 'manual' 
  - filePath: 'src/install/mysql/windows/enable-mysql-server.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: windows
            options:
              - value: 'manual' 
  - filePath: 'src/install/mysql/windows/update-config-windows.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: windows
            options:
              - value: 'manual'
  - filePath: 'src/install/mysql/find-data.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: windows
            options:
              - value: 'manual' 


  # - filePath: 'src/install/mysql/linux/update-config-apt.mdx'
  #   overrides: 
  #     - isConditionalStep: true
  #       selectedOptions: 
  #         - optionType: dropdown1
  #           options: 
  #             - value: 'linux'
  #         # Apply AND logic: linux AND apt
  #         - optionType: deployment
  #           options:
  #             - value: 'apt'
  # - filePath: 'src/install/mysql/linux/update-config-yum.mdx'
  #   overrides: 
  #     - isConditionalStep: true
  #       selectedOptions: 
  #         - optionType: dropdown1
  #           options: 
  #             - value: 'linux'
  #         # Apply AND logic: linux AND yum
  #         - optionType: deployment
  #           options:
  #             - value: 'yum'
  # - filePath: 'src/install/mysql/windows/update-config-windows.mdx'
  #   overrides: 
  #     - isConditionalStep: true
  #       selectedOptions: 
  #         - optionType: dropdown1
  #           options: 
  #             - value: 'windows'
  #         - optionType: deployment
  #           options:
  #             - value: 'windows'
        
  # - filePath: 'src/install/mysql/enable-mysql-server.mdx'
  # - filePath: 'src/install/mysql/default-install-linux.mdx'
  #   overrides: 
  #       - filePath: 'src/install/mysql/linux/install-linux.mdx'
  #         selectedOptions: 
  #           - optionType: dropdown1
  #             options: 
  #               - value: 'linux'
  #       - filePath: 'src/install/mysql/windows/install-windows.mdx'
  #         selectedOptions: 
  #           - optionType: dropdown1
  #             options: 
  #               - value: 'windows'
  #           - optionType: deployment
  #             options:
  #             - value: 'windows'
  #       - filePath: 'src/install/mysql/k8/install-k8.mdx'
  #         selectedOptions: 
  #           - optionType: dropdown1
  #             options: 
  #               - value: 'k8'
  #       - filePath: 'src/install/mysql/amazonECS/install-amazonECS.mdx'
  #         selectedOptions: 
  #           - optionType: dropdown1
  #             options: 
  #               - value: 'ecs'
  # - filePath: 'src/install/mysql/default-configuration.mdx'
  #   overrides: 
  #     - filePath: 'src/install/mysql/configure-mysql.mdx'
  #       selectedOptions: 
  #         - optionType: dropdown1
  #           options: 
  #             - value: 'linux'
  #             - value: 'windows'
  #     - skip: true
  #       selectedOptions:
  #         - optionType: dropdown1
  #           options:
  #             - value: 'k8'
  #             - value: 'ecs'
  # - filePath: 'src/install/mysql/find-data.mdx'
  # - filePath: 'src/install/mysql/update-integration.mdx'
  #   overrides:
  #     - filePath: 'src/install/mysql/k8/update-integration-k8.mdx'
  #       selectedOptions:
  #         - optionType: dropdown1
  #           options:
  #             - value: 'k8'
  #     - skip: true
  #       selectedOptions:
  #         - optionType: dropdown1
  #           options:
  #             - value: 'ecs'
whatsNextFilePath: 'src/install/mysql/whatsNext.mdx'
