agentName: rabbitmq
agentType: integration
title: 'RabbitMQ monitoring integration'
metaDescription: 'Install the RabbitMQ integration'
introFilePath: 'src/install/rabbitmq/intro.mdx'
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your environment'
    options: 
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'
        recommendedGuided: true
      - value: 'windows'
        displayName: 'Windows'
        logo: 'windows'
        recommendedGuided: true
      - value: 'ecs'
        displayName: 'ECS'
        logo: 'amazonECS'
      - value: 'kubernetes'
        displayName: 'Kubernetes'
        logo: 'k8'
      - value: 'ansible'
        displayName: 'Ansible'
        logo: 'linux'

  - optionType: deployment
    label: "Choose your install path"
    placeholder: "Choose one:"
    options:
      - value: "msi"
        displayName: "Install using MSI files (Windows)"
        logo: 'windows'
        recommendedGuided: true        
      - value: "apt"
        displayName: "Install using Apt (Debian, Ubuntu)"
        recommendedGuided: true        
      - value: "yum"
        logo: 'linux'      
        displayName: "Install using Yum (Amazon Linux, CentOS, RHEL)"
        recommendedGuided: true        
      - value: "zypper"
        displayName: "Install using Zypper (SLES)"
        recommendedGuided: true        
        logo: 'linux'        
      - value: "tar"
        displayName: "Install from tarball (Other Linux distros)"  
        recommendedGuided: true        
        logo: 'linux'    
  
steps:
  - filePath: 'src/install/rabbitmq/appInfo.mdx'
  - filePath: 'src/install/rabbitmq/default-requirements.mdx'
    overrides: 
        - filePath: 'src/install/rabbitmq/kubernetes/requirements-k8s.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'kubernetes'
        - filePath: 'src/install/rabbitmq/ecs/requirements-ecs.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'ecs' 
        - filePath: 'src/install/rabbitmq/ansible/requirements-ansible.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'ansible' 
  - filePath: 'src/install/rabbitmq/install-infra.mdx'
  - filePath: "src/install/rabbitmq/linux/install-apt.mdx"
    overrides: 
        - filePath: "src/install/rabbitmq/linux/install-apt.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "apt"
        - filePath: "src/install/rabbitmq/linux/install-tarball.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "tar"
        - filePath: "src/install/rabbitmq/linux/install-yum.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "yum"
        - filePath: "src/install/rabbitmq/linux/install-zypper.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "zypper"
        - filePath: "src/install/rabbitmq/windows/install-msi.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "msi"  
  - filePath: 'src/install/rabbitmq/linux/install-linux.mdx'
    overrides: 
        - filePath: 'src/install/rabbitmq/linux/install-linux.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'linux'
        - filePath: 'src/install/rabbitmq/windows/install-windows.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'windows'  
        - filePath: 'src/install/rabbitmq/ecs/install-ecs.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'ecs'
        - filePath: 'src/install/rabbitmq/kubernetes/install-k8s.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'kubernetes'  
        - filePath: 'src/install/rabbitmq/ansible/install-ansible.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'ansible'  

  - filePath: 'src/install/rabbitmq/find-data.mdx'
whatsNextFilePath: 'src/install/rabbitmq/whatsNext.mdx'
