agentName: snowflake
agentType: integration
title: 'Snowflake monitoring integration'
metaDescription: 'Install the Snowflake integration'
introFilePath: 'src/install/snowflake/intro.mdx'
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your environment'
    options: 
      - value: 'windows'
        displayName: 'Windows'
        logo: 'windows'

steps:
  - filePath: 'src/install/snowflake/install-infra.mdx'
  - filePath: 'src/install/snowflake/configure-integration.mdx'
  - filePath: 'src/install/snowflake/find-data.mdx'
whatsNextFilePath: 'src/install/snowflake/whatsNext.mdx'