agentName: vsphere
agentType: integration
title: 'vSphere monitoring integration'
metaDescription: 'Install the vSphere integration'
redirects:
  - /docs/infrastructure/host-integrations/host-integrations-list/vmware-vsphere-monitoring-integration
  - /docs/integrations/host-integrations/host-integrations-list/vmware-vsphere-monitoring-integration
  - /docs/vmware-esxi-open-source-integration
  - /docs/integrations/host-integrations/open-source-host-integrations-list/vmware-esxi-open-source-integration
  - /docs/integrations/host-integrations/host-integrations-list/vmware-esxi-integration
  - /docs/integrations/host-integrations/host-integrations-list/vmware-esxi-monitoring-integration
  - /docs/vmwarevsphere-integration-new-relic-infrastructure
introFilePath: 'src/install/vsphere/intro.mdx'
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your environment'
    options: 
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'
      - value: 'windows'
        displayName: 'Windows'
        logo: 'windows'
  - optionType: deployment
    label: "Choose your install path"
    placeholder: "Choose one:"
    options:
      - value: "msi"
        displayName: "Install using MSI files (Windows)"
        logo: 'windows'      
      - value: "apt"
        displayName: "Install using Apt (Debian, Ubuntu)"      
      - value: "yum"
        logo: 'linux'      
        displayName: "Install using Yum (Amazon Linux, CentOS, RHEL)"  
      - value: "zypper"
        displayName: "Install using Zypper (SLES)"     
        logo: 'linux'        
      - value: "tar"
        displayName: "Install from tarball (Other Linux distros)"       
        logo: 'linux'                  


steps:
  - filePath: 'src/install/vsphere/appInfo.mdx'
  - filePath: 'src/install/vsphere/prepare.mdx'  
  - filePath: 'src/install/vsphere/install-infra.mdx'
  - filePath: "src/install/vsphere/linux/install-apt.mdx"
    overrides: 
        - filePath: "src/install/vsphere/linux/install-apt.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "apt"
        - filePath: "src/install/vsphere/linux/install-tarball.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "tar"
        - filePath: "src/install/vsphere/linux/install-yum.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "yum"
        - filePath: "src/install/vsphere/linux/install-zypper.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "zypper"
        - filePath: "src/install/vsphere/windows/install-msi.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "msi"                   
  - filePath: 'src/install/vsphere/default-install-linux.mdx'
    overrides: 
        - filePath: 'src/install/vsphere/linux/install-linux.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'linux'
        - filePath: 'src/install/vsphere/windows/install-windows.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'windows'  
  - filePath: 'src/install/vsphere/users.mdx'                       
  - filePath: 'src/install/vsphere/find-data.mdx'
whatsNextFilePath: 'src/install/vsphere/whatsNext.mdx'
