agentName: workflow-template
agentType: integration
title: 'Use a template to create a Workflow automation'
metaDescription: 'Create a workflow automation using a template in New Relic'
redirects:
introFilePath: 'src/install/workflow-automation-template/intro.mdx'
appInfo: 
  - optionType: dropdownmenu
    label: ''
    placeholder: 'Select a template'
    options: 
      - value: 'Startertemplate'
        displayName: 'Starter template'
        logo: ''
        recommendedGuided: true
      - value: 'Sendreport'
        displayName: 'Send a report to Slack'
        logo: ''
        recommendedGuided: true
      - value: 'APIGatewayRollback'
        displayName: 'API gateway rollback'
        logo: ''
        recommendedGuided: true
      - value: 'EC2InstanceManagement'
        displayName: 'EC2 instance management'
        logo: ''
        recommendedGuided: true
steps:
  - filePath: 'src/install/workflow-automation-template/appInfo.mdx'
  - filePath: 'src/install/workflow-automation-template/default-requirements.mdx'
  - filePath: 'src/install/workflow-automation-template/startertemplate/overview.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdownmenu
            options:
              - value: 'Startertemplate'
  - filePath: 'src/install/workflow-automation-template/startertemplate/create-starter-template.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdownmenu
            options:
              - value: 'Startertemplate'
  - filePath: 'src/install/workflow-automation-template/send-report-to-slack.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdownmenu
            options:
              - value: 'Sendreport'
  - filePath: 'src/install/workflow-automation-template/api-gateway-rollback.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdownmenu
            options:
              - value: 'APIGatewayRollback'
  - filePath: 'src/install/workflow-automation-template/ec2-instance-management.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: dropdownmenu
            options:
              - value: 'EC2InstanceManagement'
whatsNextFilePath: 'src/install/workflow-automation-template/whatsNext.mdx'