name: Generate Agent Release Notes

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # 7PM PDT

jobs:
  generate-json:
    name: Generate JSON
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.4

      - run: yarn install --frozen-lockfile

      - name: generate and upload
        run: scripts/releaseNotes.mjs --upload
