name: Check for Keys

on:
  pull_request:
    types:
      - opened
    branches:
      - develop

jobs:
  check-for-keys:
    name: Check for keys in files and commit history
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Check for keys
        run: ./scripts/actions/check-for-keys.sh
