# To collect build duration & memory usage, we trigger two builds
# So we get cold and warm build timings. This is for the cold build.
name: First Build
on:
  schedule:
    - cron: '0 12 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: zzzze/webhook-trigger@v1.0.0
        with:
          # Webhook URL one gets from Site Settings > General
          webhook_url: https://webhook.gatsbyjs.com/hooks/data_source/publish/e59971ce-b059-4218-93c8-b0752b2b4ffb
