name: Manually Add Slugs to Translation Queue

on:
  workflow_dispatch:
    inputs:
      files:
        description: 'String of filenames separated by comma (src/content/docs/...)'
        required: true
        type: string
      machineTranslation:
        description: 'Send for machine translation'
        required: false
        type: boolean
      locale:
        description: 'Define locale'
        required: false
        type: string

env:
  DB_CONNECTION_INFO: ${{ secrets.DB_CONNECTION_INFO }}
  HUMAN_TRANSLATION_PROJECT_ID: ${{ secrets.TRANSLATION_VENDOR_PROJECT }} # human project id
  MACHINE_TRANSLATION_PROJECT_ID: ${{ secrets.TRANSLATION_VENDOR_MT_PROJECT }} # machine project id
  NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
  NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}

jobs:
  get-and-save-slugs:
    name: Get and Save Slugs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Cache dependencies
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Get slugs and save
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn manual-add-files-to-translate -f ${{ github.event.inputs.files }} -l ${{ github.event.inputs.locale }} -mt ${{ github.event.inputs.machineTranslation }}
