name: Trigger i18n merge

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  merge-main-i18n-branches:
    name: Merge main to i18n branches
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.4

      - name: Cache dependencies
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Check for modified files & merge
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_ENG_BOT_TOKEN }}
          SOURCE_REF: ${{ github.ref }}
        run: |
          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
          yarn trigger-i18n-merge -u $URL
