name: Upload Agent Release Notes Metadata

on:
  push:
    branches:
      - main
    paths:
      - 'src/content/docs/release-notes/**/*.mdx'

jobs:
  upload-metadata:
    name: Upload Release Notes Metadata to NewRelic
    runs-on: ubuntu-latest
    timeout-minutes: 5

    if: github.event.pull_request.head.repo.full_name == github.repository || github.event_name != 'pull_request'

    steps:
      - name: Upload agent metadata
        uses: newrelic/agent-metadata-action@v1
        with:
          newrelic-client-id: ${{ secrets.NEWRELIC_CLIENT_ID }}
          newrelic-private-key: ${{ secrets.NEWRELIC_PRIVATE_KEY }}
          fetch-depth: '10'
          newrelic-license-key: ${{ secrets.APM_CONTROL_NR_LICENSE_KEY }}

