name: validate javascript functionality

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  NODE_OPTIONS: '--max-old-space-size=4096'
  CHOKIDAR_USEPOLLING: 1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WEBDRIVER_ENV: main

jobs:
  test:
    name: webdriver test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.4

      - name: Cache dependencies
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: run webdriver on desktop
        run: yarn webdriver-desktop

      - name: run webdriver on mobile
        run: yarn webdriver-mobile
